project:
  type: book
  output-dir: output

metadata-files:
  - ./metadata/_format.yml
  - ./metadata/_website.yml

number-sections: true

mainfont: "Times New Roman"
sansfont: "Arial"
monofont: "Courier New"
mathfont: "TeX Gyre Termes Math"

book:
  title: "Aligning business processes with regulatory requirements"
  subtitle: "a systematic literature review"
  downloads: [pdf,docx]
  search: true
  repo-url: https://github.com/jan-ru/phd_kul
  author: 
    - name: "Jan-Ru Muller"
      orcid: 0000-0003-1689-0557
      email: janru.muller@edu.vlerick.com
      affiliations:
      - name: Amsterdam University of Applied Sciences
        address: Fraijlemaborg 133
        city: Amsterdam
        country: The Netherlands
        postal-code: 1102 CV
      - name: Vlerick Business School
        address: Reep 1
        city: Ghent
        country: Belgium
        postal-code: 9000
  date: today
  date-format: "DD/MM/YYYY"

  chapters:
    - index.qmd
    - s2_slr_doc_1.qmd
    - s2_slr_doc_2.qmd
    - s2_slr_doc_3.qmd
    - s2_slr_doc_4.qmd
    - s2_slr_doc_5.qmd

  appendices:
    - s2_slr_doc_a_databases_searched.qmd
    - s2_slr_doc_b_basket_of_11.qmd
    - s2_slr_doc_c_literature_selection.qmd
    - s2_slr_doc_d_literature_found.qmd
    - s2_slr_doc_e_calculations.qmd
    - s2_slr_doc_f_journals.qmd
    - s2_slr_doc_g_authors.qmd
    - s2_slr_doc_h_keywords.qmd

license: "CC BY"

bibliography: MyLibrary.bib
#  main: MyLibrary.bib
#  software: MySoftware.bib

#citeproc: false

#filters:
#  - multibib
#validate-yaml: false
