project:
  type: book

book:
  title: "The initial 100 papers"
  author: 
    - name: "Jan-Ru Muller"
      affiliations:
      - Vlerick Business School
      - Hogeschool van Amsterdam
  date: "7/9/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - part: part1.qmd
      chapters:
        - s0_research_questions.qmd
        - s1_articles.qmd
        - s2_slr.qmd
        - s3_methods.qmd
        - s4_results
    - references.qmd

  appendices:
    - z_backlog.qmd
    - z_resources.qmd
    - z_journals.qmd
    - z_software.qmd

bibliography: Top100.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



