project:
  type: book

book:
  title: "The initial 100 papers"
  author: 
    - name: "Jan-Ru Muller"
      affiliations:
      - Vlerick Business School
      - Hogeschool van Amsterdam
  date: "7/9/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - s2_case_link2law.qmd
    - references.qmd

  appendices:
    - z_backlog.qmd
bibliography: Top100.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
