project:
  type: book
  output-dir: output
format:
  pdf:
    papersize: a4
    documentclass: scrreprt
    toc: true
    lof: true
    lot: true
  html: default

mainfont: "Times New Roman"
sansfont: "Arial"
monofont: "Courier New"
mathfont: "TeX Gyre Termes Math"

include-in-header: 
      text:
        \usepackage{imakeidx, bibentry, multicol}

book:
  title: "Aligning business processes with regulatory requirements"
  subtitle: "a systematic literature review"
  author: 
    - name: "Jan-Ru Muller"
      orcid: 0000-0003-1689-0557
      email: janru.muller@edu.vlerick.com
      affiliations:
      - name: Amsterdam University of Applied Sciences
        address: Fraijlemaborg 133
        city: Amsterdam
        country: The Netherlands
        postal-code: 1102 CV
      - name: Vlerick Business School
        address: Reep 1
        city: Ghent
        country: Belgium
        postal-code: 9000
  date: "3/25/2024"
  date-format: "DD/MM/YYYY"

  chapters:
    - index.qmd
    - s2_slr_doc_.qmd

  appendices:
    - s2_slr_doc_a_databases_searched.qmd
    - s2_slr_doc_b_basket_of_11.qmd
    - s2_slr_doc_c_ris2py_script.qmd
    - s2_slr_doc_d_literature_selection.qmd
    - s2_slr_doc_e_literature_found.qmd
    - s2_slr_doc_f_calculations.qmd
    - s2_slr_doc_g_abstracts.qmd
    - s2_slr_doc_h_jo_au_kw.qmd

license: "CC BY"
latex-output-dir: output
bibliography: MyLibrary.bib
