---
title: "Managing Business Processes for Agility and Regulatory Compliance"
subtitle: "Design Science Research"
date: "10-14-2023"
date-format: "D/MM/YYYY"
date-modified: "10-14-2023"

author:
  name: Jan-Ru Muller
  orcid: 0000-0003-1689-0557
  email: j.r.muller@hva.nl
  affiliations:
    - name: Amsterdam University of Applied Sciences
      department: Faculty of Business and Economics
      url: https://www.amsib.com
    - name: Vlerick Busines School
      department: Technology and Operations Management
      url: https://www.vlerick.com

abstract: ""
format:
  pdf:
    cite-method: citeproc
    include-in-header: 
      text:
        \usepackage{imakeidx, orcidlink, totcount, bibentry}
        \regtotcounter{table}
        \regtotcounter{figure}
        \makeindex
        \makeindex[name=authors, title=Authors, intoc=True]
        \makeindex[name=affiliations]
        \renewcommand\refname{References (\total{citenum})}
    include-after-body: 
      text:
        \printindex
        \printindex[authors]
toc: false
toc-depth: 2
bibliography: MyLibrary.bib
keywords: modelling languages, controlled natural language, extentions, compliance, MDE, Accounting, Rulebase, ERP, Compliance (Risk Management), Enterprise Achitecture

---

# Introduction

Right at the start I have to mention the thesis of Mariette Lokin that is the inspiration for this project. Her research is about the interaction between law, excution and ICT. "The goal of the performed PhD-research was to develop an approach for agile law making, not only aiming at legislation as a product, but also as a process" (lokinAgileLawMaking2020).

I have contacted Mariette Lokin to discuss her research and the possibility of doing a related study assuming the point of view CxO of a company. We discussed a scenario where a (tax) authority can provide a company with a law-based knowledge model that the company can then use to base its processes on.

Connecting regulations with requirements is a long standing topic of research(@breauxRegulatoryComplianceExtracting2006). Our research intents to help reduce the inefficiencies currently associated with the implementation of regulatory changes. In the case of regulatory compliance there is work to be done for both regulators and corporations improve upon the status quo.

\index[authors]{Lokin, Mariette\orcidlink{0000-0003-4415-5429}}
\index[authors]{Travis, Breaux\orcidlink{0000-0001-7127-8155}}

# Background

Regulatory changes, or any changes for that matter, require corporations to adapt their processes. Change of processes almost always touches IT and almost always requires an IT systems change. So what? Well, unfortunately, IT (core) systems tend to be difficult to adapt to changing conditions. "The average bank spends approximately 40% to 60% of its change budget on regulatory compliance" [@gittfriedWhenAgileMeets2017]. On the one hand corporations are faced with a requirement to be flexible. On the other hand they are faced with severe IT system inertia. 

Why is this alarming? Current developments, as recent as the UN Climate Change Conference in Glasgow, suggest companies will need to keep on improving on there ability to adjust to a changing regulatory environment. Change is not stopping. If anything, change is speeding up. Boards will order, either voluntarily or mandatory,  the adoption of new standards like those stemming from the Global Reporting Initiative. Consequently, ongoing and increasing pressure on the IT function is to be expected (reference).

Who cares? The short answer: everybody working in industries with a strong reliance on IT. This paper is about two disciplines that are intimately woven into the corporate fabric : Business Process Management (BPM) and Enterprise Risk Management (ERM) both require flexibility from the supporting IT systems. 

BPM involves "overseeing how work is performed in an organisation" [@dumasFundamentalsBusinessProcess2013]. BPM is a long-standing academic discipline that is also widely applied in practice. The field has matured over the last 25 years and features standard textbooks like those from Weske [@Weske2007BusinessPM] and  @vanderaalstBusinessProcessManagement2013. There is ample research about (business) process design, operation, optimisation, analysis, and compliance.

\index[authors]{Aalst, Wil van der \orcidlink{0000-0002-0955-6940}}
\index[authors]{Dumas, Marlon \orcidlink{0000-0002-9247-7476}}
\index[authors]{Mendling, Jan \orcidlink{0000-0002-7260-524X}}
\index[authors]{Reijers, Hajo \orcidlink{0000-0001-9634-5852}}
\index[authors]{La Rosa, Marcello \orcidlink{0000-0001-9568-4035}}
\index[authors]{Weske, Mathias \orcidlink{0000-0002-3346-2442}}

ERM involves "providing an organization both resilience and opportunity in the face of uncertainty" [@linkeEnterpriseRiskManagement2019]. Regulatory compliance management, a subfield of ERM, may be considered a value added application of BPM. Hence, there is an interest in regulatory compliance management from the BPM community. Sadiq calls BPM "a driver for regulatory compliance" [@sadiqManagingRegulatoryCompliance2010]. There are arguments for and against closely coupling BPM and ERM [@ramezaniSeparatingComplianceManagement2011]. Yet, there is a general consensus that both concepts have an intersecting area of application [@sadiqMethodologicalFrameworkAligning2009].

\index[authors]{Linke, Arthur \orcidlink{0000-0002-1977-8686}}
\index[authors]{Governatori, Guido \orcidlink{0000-0002-9878-2762}}

## Scope

The scope of the research is defined by: geography, company sector, company size, type of regulation. In a previous iteration of the research idea the selected geography was Europe, the selected sector was Financial Institutions, the company size was listed companies, the type of regulation was required disclosure on risks (Non-Financial Reporting Directive).

In the current research idea the geographic scope has been limited to the Benelux. There is no longer a specific sector selected. The companies selected are companies with more than 100 employees. The regulation selected is the Corporate Sustainability Reporting Directive (CSRD).

In the literature a distinction is made between "conceptual modelling languages", for example petrinets, and "languages accessible to domain experts", for example BPMN (@lohmannComplianceDesignArtifactcentric2013). I would like the study to focus on "end-to-end" (terms to be defined), i.e. not limited to only technical users or only business users.

\index[authors]{Lohmann, Niels \orcidlink{0000-0001-9037-795X}}
\index[authors]{Sadiq, Shazia \orcidlink{0000-0001-6739-4145}}

## Research Objectives

To design, implement, and evaluate a prototype system that enables companies to translate (an aspect of) the CSRD into requirements that ensure the business processes are run in accordance with the regulation and yield result that are compliant with the regulation.

Aspects of CSRD are environmental, social and governance. Which aspect to select is to be decided.

The system will be judged on useability, where "useability" is still to be defined.

## Problem statement

Both BPM and ERM are core disciplines in Financial Services. Our research focuses on BPM where it relates to ERM and indeed, more specifically, where BPM relates to regulatory compliance. In our research the focus is on BPM effectiveness, the ability to change processes according to new or changed external regulatory demands and requirements. 

Existing research on "BPM as a driver for regulatory compliance" is around both technical and organizational topics. Technical topics, for example, include descriptions of how processes shall be modelled to ensure compliance [@sadiqModelingControlObjectives2007]. Also, there is research is around business process compliance frameworks [@hashmiEvaluatingBusinessProcess2015] and [@kharbiliFrameworkSemanticBusiness2008]. Recent research centered around the problem of the mismatch between the language in which regulations are expressed versus the languages in which business processes are expressed [@corsiusRegelSpraakCNLExecutable2021]. Without a clear link between (external) regulatory requirements and the (internal) business processes, the extent to which new regulations have been properly implemented in the company processes is not always clear.

\index[authors]{Fahland, Dirk \orcidlink{0000-0002-1993-9363}}
\index[authors]{Ramezani, Elham} 
\index[authors]{Werf, Jan Martijn van der \orcidlink{0000-0002-7264-381X}}
\index[authors]{Mattheis, Peter}

## Research questions

RQ-1: What are the best practices for aligning business processes with regulatory requirements to achieve regulatory compliance by design?

RQ-2: How to manage the design and operation of business processes that support regulatory compliance with the CSRD.

RQ-3: How to extract business rules from the CSRD regulation and how to transform these rules for incorporation into business processes. 

RQ-4: How can the effectiveness of the proposed methods in reducing the risk of non-compliance be evaluated?

## Research Method

The proposed research methodology is based on the design science research framework created by Hevner et al. [@hevnerDesignScienceInformation2004]. The intended research outcome is an artefact, a set of methods, providing guidance to practitioners with respect to business process design and management mechanisms. The research focuses on a subclass of business processes: those businesses processes related to regulatory compliance.

\index[authors]{Hevner, Alan \orcidlink{0000-0003-4953-3900}}

## Possible Contributions

First, we'll perform a systematic literature review (SLR) with the intended outcome to define the research gap on the subject of this paper. If we find current research on "design for compliance" then probably the Benelux geographic context en the focus on (one aspect of) CSRD may still be a novel angle.

Second, we'll model (an aspect) of the CSRD and translate the model to requirements for an (ERP) information system. 

Third, we'll check the requirements against one or two common (ERP) systems as used in practice.

Fourth, we'll hope to demonstrate that implementation of new regulations is aided if the regulator, or a regulators agent, not only provides for the rules but also provides for template processes for companies to adopt.

{{< pagebreak >}}

# Next step: Literature Review

The planning of the SLR is the subject of the next update (in November). The steps in the planning are from @keeleGuidelinesPerformingSystematic2007.

In the "study quality assessment phase" the studies retrieved from databases will, among others, be compared to a list of eligable journals. From a podcast by @ThisIsResearch, I understand in the field of IS research there is a "basket of 8" authoritive journals (table 1). The columns: level and impact factor (IF) are taken from the Vlerick Strategic Journal List (the List), effective as of January 2020. Empty means the journal is not on the List.

\index[authors]{Recker, Jan \orcidlink{0000-0002-2072-5792}}
\index[authors]{Berente, Nicholas \orcidlink{0000-0002-1403-4696}}

| Journal Title                                                              |Level| IF  |
|----------------------------------------------------------------------------|:---:|:---:|
| MIS Quarterly ([MISQ][MISQ-ref])                                           | A*  |7,268|
| Journal of Management Information Systems ([JMIS][JMIS-ref])               | A*  |2,744|
| Information Systems Journal ([ISJ][ISJ-ref])                               | A   |4,267|
| Journal of the Association for Information Systems ([JAIS][JAI-ref])       | A   |2,839|
| Communications of the Association for Information Systems ([CAIS][CAI-ref])| A   |  ?  |
| Information Systems Research ([ISR][ISR-ref])                              | A*  |2,301|
| Journal of Information Technology ([JIT][JIT-ref])                         | A   |4,435|
| European Journal of Information Systems ([EJIS][EJIS-ref])                 | A   |2,819|

: Basket of 8 {#tbl-journals}

[MISQ-ref]: https://misq.umn.edu/
[JMIS-ref]: https://jmis-web.org/
[ISJ-ref]: https://onlinelibrary.wiley.com/journal/13652575
[JAI-ref]: https://aisel.aisnet.org/jais/
[CAI-ref]: https://aisel.aisnet.org/cais/
[ISR-ref]: https://pubsonline.informs.org/journal/isre
[JIT-ref]: https://journals.sagepub.com/home/jina
[EJIS-ref]: https://www.tandfonline.com/toc/tjis20/current

The list of 8 premier journals exists since 2011. The list has been updated in 2023 to include an additional 3 journals.

| Journal Title                                                              |Level| IF  | 
|----------------------------------------------------------------------------|:---:|:---:|
| Decision Support Systems ([DSS][DSS-ref])                                  |  A  |2,819|
| Information & Management ([IAM][IAM-ref])                                  |  A  |3,890|
| Information and Organization ([IAO][IAO-ref])                              |     |     |

: Recent additions {#tbl-journalsb}

[DSS-ref]: https://www-sciencedirect-com/journal/decision-support-systems
[IAM-ref]: https://www.sciencedirect.com/journal/information-and-management
[IAO-ref]: https://www-sciencedirect-com/journal/information-and-organization

Next to the basket of 8 (now 11) there are other journals that I will want to search articles from. BISE is of interest because it is an european (IS) journal (as is EJIS). BPMJ and IJDG may be of interest given the subject matter their titles refer to. SMR I find of interest as it focusses on the intersection of Management and Technology. On the topic of work design and agility I may want to reference works of [Nelson Repenning](https://mitsloan.mit.edu/faculty/directory/nelson-p-repenning). HBR maybe of interest for the (historic) articles on business process reengineering by [Michael Hammer](https://hbr.org/2008/10/remembering-mike-hammer).

\index[authors]{Repenning, Nelson \orcidlink{0000-0001-9832-131X}}

In terms of "where does one aim to be published", for an entirely different type of journal: JOSS. JOSS doesn't show on any of the quality journal lists. Yet, it seems an appropriate outlet for part of the work produced in the context of my PhD research. My research follows a design science methodology. "In order to add science to Design Science, developed artifacts need to be properly evaluated" [@mijacEvaluationDesignScience2019].

\index[authors]{Mijač, Marko \orcidlink{0000-0003-1382-3156}}

| Journal Title                                                            |Level| IF  |
|--------------------------------------------------------------------------|:---:|:---:|
| Business Process Management Journal ([BPMJ][BPMJ-ref])                   |     |     |
| Business & Information Systems Engineering ([BISE][BISE-ref])            |     |     |
| Journal of Disclosure and Governance ([IJDG][IJDG-ref])                  |     |     |
| Sloan Management Review ([SMR][SMR-ref])                                 | A*  |0,971|
| Harvard Business Review ([HBR][HBR-ref])                                 | A*  |0,720|
| Journal of Open Source Software ([JOSS][JOSS-ref])                       |     |     |

: Other journals of interest {#tbl-journalsc}

[BPMJ-ref]: https://www.emeraldgrouppublishing.com/journal/bpmj
[BISE-ref]: http://www.bise-journal.com/
[IJDG-ref]: https://www.palgrave.com/gp/journal/41310
[SMR-ref]: https://sloanreview.mit.edu/
[HBR-ref]: https://hbr.org/
[JOSS-ref]: https://www.emeraldgrouppublishing.com/journal/bpmj

It is important to define the field the research is positioned in: I still will look into "business informatics". This is a term less used in the U.S. and more used in the E.U. ("bedrijfsinformatica" in Dutch and "wirtschaftsinformatik" in German).

{{< pagebreak >}}

# Planning (proposal)

|   |month| week| startdate | hva   | deliverable                 | status |
|:-:|-----|:---:|:---------:|:-----:|:----------------------------|--------|
| ->| oct.|  42 |16-10-2023 |       |Research Idea                |Update2 |
|   | oct.|  43 |23-10-2023 |holiday|                             |        |
|   | oct.|  44 |30-10-2023 |       |                             |        |
|   | nov.|  45 |06-11-2023 |       |SLR Planning                 |Update3 |
|   | nov.|  46 |13-11-2023 |       |                             |        |
|   | nov.|  47 |20-11-2023 |       |SLR Indentification of       |        |
|   | nov.|  48 |27-11-2023 |       |Research                     |Update4 |
|   | dec.|  49 |04-12-2023 |       |                             |        |
|   | dec.|  50 |11-12-2023 |       |SLR Study Selection          |        |
|   | dec.|  51 |18-12-2023 |       |                             |Update5 |
|   | dec.|  52 |25-12-2023 |holiday|SLR Study Quality Assessment |        |
|   | jan.|  01 |01-01-2024 |holiday|                             |        |
|   | jan.|  02 |08-01-2024 |       |                             |        |
|   | jan.|  03 |15-01-2024 |       |SLR Data Extraction          |Update6 |
|   | jan.|  04 |22-01-2024 |       |                             |        |
|   | jan.|  05 |29-01-2024 |       |SLR Data Synthesis           |        |
|   | feb.|  06 |05-02-2024 |       |                             |        |
|   | feb.|  07 |12-02-2024 |       |SLR Report                   |Update7 |
|   | feb.|  08 |19-02-2024 |       |                             |        |
|   | feb.|  09 |26-02-2024 |       |PS Planning                  |        |
|   | mar.|  10 |04-03-2024 |       |                             |        |
|   | mar.|  11 |11-03-2024 |       |                             |Update8 |
|   | mar.|  12 |18-03-2024 |       |                             |        |
|   | mar.|  13 |25-03-2024 |       |DBA Research Day             |        |
|   | apr.|  14 |01-04-2024 |       |                             |        |
|   | apr.|  15 |08-04-2024 |       |To be determined             |Update9 |
|   | apr.|  16 |15-04-2024 |       |                             |        |
|   | apr.|  17 |22-04-2024 |       |                             |        |
|   | apr.|  18 |29-04-2024 |holiday|                             |        |
|   | mei |  19 |06-05-2024 |       |To be determined             |Update10|
|   | mei |  20 |13-05-2024 |       |                             |        |
|   | mei |  21 |20-05-2024 |       |                             |        |
|   | mei |  22 |27-05-2024 |       |                             |        |
|   | jun.|  23 |03-06-2024 |       |Deadline Research Proposal   |Update11|
|   | jun.|  24 |10-06-2024 |       |Research week                |        |
|   | jun.|  25 |17-06-2024 |       |                             |        |
|   | jun.|  26 |24-06-2024 |       |                             |        |
|   | jul.|  27 |01-07-2024 |holiday|                             |        |

{{< pagebreak >}}

# References
