---
title: "SLR"
subtitle: "Protocol"
date: "10-23-2023"
date-format: "D/MM/YYYY"
date-modified: "10-23-2023"
author:
  - name:
    orcid: 0000-0003-1689-0557
    email: j.r.muller@hva.nl
    affiliations:
      - name: Amsterdam University of Applied Sciences
        address: Fraijlemaborg 133
        city: Amsterdam
        postal-code: 1102 CV
      - name: Vlerick Business School
        address: Reep 1
        city: Ghent
        postal-code: 9000
abstract: ""
format:
  pdf:
    cite-method: citeproc
    include-in-header: 
      text:
        \usepackage{imakeidx, bibentry}
toc: false
toc-depth: 2
bibliography: MyLibrary.bib
keywords: modelling languages, controlled natural language

---
# Systematic Literature Review

## My Zotero Library
[05/07/2023] Looking in my Zotero library for articles with a title that contains "systematic literature review", the result is 7 hits.

The first is @kitchenhamGuidelinesPerformingSystematic2007 and there is a duplicate @keeleGuidelinesPerformingSystematic2007. Second there are 3 SLR's where Van Looy is co-author (@moreno-montesdeocaSystematicLiteratureReview2015, @ahmadBusinessProcessManagement2020, @prodanovaHowBeneficialSocial2019). There is 1 SLR about BPMN extentions (@zarourSystematicLiteratureReview2019) Finally, there is one SLR about Open Science (@VICENTESAEZ2018428) which is not relevant to BP4RC.


** Create Zotero(?) report whereby I get abstract, methodology etc. of paper.

** How to reference multiple papers? - numeric method **
## Need for SLR

This SLR is undertaken as a sprelude to further research.

- What are the review’s objectives?
- What sources were searched to identify primary studies? Were there any restrictions?
- What were the inclusion/exclusion criteria and how were they applied? 
- What criteria were used to assess the quality of primary studies? 
- How were quality criteria applied? 
- How were the data extracted from the primary studies? 
- How were the data synthesised? 
- How were differences between studies investigated? 
- How were the data combined? 
- Was it reasonable to combine the studies? 
- Do the conclusions flow from the evidence?

## Commissioning Document

A4 in attachment (not required for PhD students ref pag 9 of Kitchenham)
- Project Title 
- Background 
- Review Questions
- Advisory/Steering Group Membership (Researchers, Practitioners, Lay members, Policy Makers etc) 
- Methods of the review 
- Project Timetable 
- Dissemination Strategy 
- Support Infrastructure 
- Budget 
- References

## Research questions

RQ-1: What are the  for aligning business processes with regulatory requirements to achieve regulatory compliance by design?

## Review protocol


keywords

Business Processes and Regulatory Compliance




Sources:

- ScienceDirect (Elsevier)[]
- Web of Science (WoS)[]
- Scopus (not available via Vlerick)
- SSNR
- arXiv > cs
- dblp, computer science bibliography 

"Regulatory Compliance"
A Semantic Model Based Framework for Regulatory Reporting Process Management
Author keywords: Events, Process extraction, Regulatory reporting, Semantic technology
Prominence percentile 99.023 (shows the current momentum of a Topic, i.e. very high)


Search strings

I want to expand the number of SLR to 10 by including SLR's from A-star journals in the BPM/IS field(s).

To demonstrate International Research Collaboration (IRC), "using affiliations listed in publications has become the standard practice" [](https://direct.mit.edu/qss/article/3/3/529/112967/Assessing-the-quality-of-bibliographic-data). I would like to use this to show the affiliations of the authors of the articles included in my literature research.

Concepts mentioned in the article:
- Data quality (DQ) and Data quality assessment (DQA)
- Functional Requirements for Bibliographic Records (FRBR)
- Zotero Data quality dimensions (DQDs)

In the article above DQ is split into:
- Intrinsic Data Quality (4 attributes)
- Contextual Data Quality (5 attributes)
- Representational Data Quality (4 attributes)
- Accessibility Data Quality (2 attributes)

Note: in this study Microsoft Academic Graph (MAG) is one of the four datasources considered. MAG has since been [retired](https://www.microsoft.com/en-us/research/project/microsoft-academic-graph/).

\newpage

Quality Evaluation Criteria

QE1 Peer reviewed journals

QE2

QE3


\newpage

## Thesis

The thesis by Mariette Lokin was published in 2018 (in Dutch) by the Vrije Universiteit Amsterdam (@lokinWendbaarWetgevenWetgever2018). It is available at the [research portal](https://research.vu.nl/en/publications/wendbaar-wetgeven).

## Research question

RQ: To what extent and in what way can digital execution of legislation by national government agencies be taken into account in the legislative process?

Five supporting research questions listed in the attachment.

## Theories/concepts mentioned in the intro

Paragraph 1.5 describes legislation as a product. Specifically it describes how technologies like language models, linked data and a formalized legal domain vocabulary can ease the translation of regulatory texts into computer programs. The identification of these three tools there are three research questions formulated (appendix, question 1,2,3)

Paragraph 1.6 describes the law making process. Specifically the question if in the law making process there is sufficient consideration for the influence of technological developments on the execution of legislation. From this observation two additions research questions are formulated (appendix, questions 4 and 5).

## Brief description of the research method

Five cases are descibed at two government agencies. Additionally, one cross-domain application is described.:

- case 1 & 2, Tax Office (Ministry of Finance), 2.4.2

- case 3 & 4, IND (Ministry of Justice) 2.4.3

- case 5, Standard Businss Reporting (cross-domain application) 2.4.4

## Conclusion

The conclusion is that there are realistic possibilities for lawmakers to take into account the digital execution by designated executive government agencies. 

- A language model aids with precise formulation and creation of specifications for digital execution.

- A legalvocabulary (CNL) provides for insight into the diversity of terminology and allows for analysis to reduce diversity.

- The application of linked data provides fof insight into the 'web' of laws and related documents for insight into applicable rules and meaning.

The future perspective is that the legal technical information on wetten.nl no longer only contains references to other regulations and case law, but also to decision rules based on the relevant article. The future perspective is that the legal technical information on "wetten.nl" no longer only contains references to other regulations and case law, but also to decision rules based on the relevant article. "In my opinion, a role for the legislator in advance in guaranteeing legal protection in automated decision-making through transparency and traceability of decision rules and algorithms is more obvious than setting up retrospective control."


## Suggestions for further research


## What is the contribution

An approach has een proposed to 

\newpage

## Translated Research Questions[^1]

RQ1 : Can a language model be created based on analysis of the structure and formulation of legislation with which legal concepts in legislation can be made unambiguously recognizable?

RQ2 : Can a useful legislative vocabulary be generated from manifestations of legal concepts based on annotation of legislation using the language model?

RQ3 : Can the use of linked data in the drafting of legislation improve insight into the legal rules relevant to the digital implementation of a specific task and insight into explanatory notes and parliamentary history?

RQ4 : What support is needed in the legal legislative process to implement the language model, to apply a legislative vocabulary and linked data?

RQ5 : What changes are necessary in the administrative-political legislative process to realize multidisciplinary cooperation in the phase of official preparation of legislation, and to give technological rationality its own place in the phase of parliamentary consideration of legislation?

[^1]: Translated from Dutch into English with Google Translate.

## Original Research Questions

OV : In hoeverre en op welke wijze kan bij het tot stand brengen van wetgeving rekening worden gehouden met digitale uitvoering door uitvoeringsorganisaties van de rijksoverheid?

OV1 : Kan op basis van analyse van de structuur en formulering van wetgeving een taalmodel worden gecreëerd waarmee juridische concepten in wetgeving eenduidig herkenbaar gemaakt kunnen worden?

OV2 : Kan op basis van annotatie van wetgeving aan de hand van het taalmodel een bruikbaar wetgevingsvocabulaire worden gegenereerd van verschijningsvormen van juridische concepten?

OV3 : Kan met toepassing van linked data bij de redactie van wetgeving het inzicht in de voor digitale uitvoering van een bepaalde taak relevante wettelijke regels en het inzicht in toelichtingen en parlementaire geschiedenis worden verbeterd?

OV4 : Welke ondersteuning is nodig in het juridische wetgevingsproces om het taalmodel, het wetgevingsvocabulaire en linked data te kunnen toepassen?

OV5 : Welke veranderingen zijn nodig in het bestuurlijk-politieke wetgevingsproces om een multidisciplinaire samenwerking te realiseren in de fase van ambtelijke voorbereiding van wetgeving, en om de technologische rationaliteit een eigen plaats te geven in de fase van parlementaire behandeling van wetgeving?

\newpage

Follow on publications:

Title [@lokinAgileLawMaking2020]


## Keyword (from articles)



## Definitions

Regulatory Compliance

Business Process Management

Agility

