---
execute:
  echo: false
---

# Review execution {#sec-review-execution}

## Research identification



## Selection of studies

The initial searches were done on all database fields. The search was subsequently made more specific by searching titles and abstracts. Lastly we searched titles, abstracts and keywords.

The WoS search yielded 29 hits. Excluding 4 articles with BPM in the title where BPM has a different meaning than "Business Process Management". For example where BPM is an abbreviation of "Biodiesel Particulate Matter". Excluding 1 article as it is a double, also ocuring in the dblp search.

The ACM search ...

The SD search yielded 7 hits. On the basis of article type (1 book chapter and 1 short communication) we have excluded two articles. An additional article was excluded as the title referred to "Business Process Management Map", which is a different concept. 

The SSRN search yielded 2 results, both excluded as they are preprints.

The arXiv search yielded 0 records when looking for articles with "Business Process Management" or BPM in the title field. Two records where found on the basis of abstract and keyword matches. All the same these records have been subsequently excluded when the exclusion criteria have been applied.

The dblp search yielded 41 records, including 2 books and 35 conference papers. After exclusion 4 records remain, 3 journal articles and one PhD thesis. For the next step, the abstract scan, the thesis has been replaced by a journal article by the same author about the same topic.

The Zenodo search yielded 0 records when looking for articles with "Business Process Management" or BPM in the title field. <!-- Four records where found on the basis of abstract and keyword matches. All the same these records have been subsequently excluded when the exclusion criteria have been applied. -->

Six additional records have been included identified via different sources: 4 journal articles, 1 PhD thesis and 1 conference paper. Here too, for the next step in the process the thesis has been replaced by a journal article by the same author about the same topic.



The abstracts of the remaining 21 articles are listed in "Abstracts", @tbl-review-abstracts.

For the final list we only consider the {{<var literature.fulltexts_included>}} articles where three or more conditions are met (see: [appendix E](#appendix-e), @tbl-full-text-included).

## Data collection

The output of each query has either been a bib file or a ris file. All bib files have been converted to ris files. The mapping of bibliographic elements to the ris fields differs per data sources. A script has been written to get to a uniform ris-format. 

The open access databases do not contain the full text articles if the articles are not open access. DBLP also doesn't contain abstracts. The absence of full text articles or abstracts is explained by constraints imposed by copyrights.

The excel file containing the article lists has been stored on zenodo for future reference ([zenodo 10795823](https://zenodo.org/records/10795823)).

## Synthesis of extracted data

<!--Relevant literature and identify topics listed as possibilities for future -->

8-12 years ago: the two oldest papers in the dataset are @vanderfeestenProductbasedWorkflowSupport2011 and @hadaschInfluenceDirectiveExplanations2016. The article of Irene Vanderfeesten is on the subject of her PhD thesis (@vanderfeesten2011product). It describes the concept of a Product Data Model which, in workflow systems, can be compared to a Bill of Material in manufacturing systems. The article doesn't mention future research but does mention collaboration with industrial partners to incorporate a PDM in a commercial tool. The Hadasch paper is a quantitive study about users' process compliance as a function of process explanations either in textual or diagram format (DE/DDE). Broadly stated, the paper concludes that the better explanations result in better compliance. Other than a recommendation that the findings of the paper be leveraged in future research, there is no specific guidance about future research.

4-8 years ago: the four papers published in the 2016-2019 timeslot are @vanderaalstSpreadsheetsBusinessProcess2018, @hashmi2017norms, @hashmiAreWeDone2018 and @vanderaaComparingTextualDescriptions2017. The van der Aalst paper compares and contrasts spreadsheet technology with process mining technology. It mentions checking for compliance as the activity whereby a process as run in reality is compared to a normative model. The article mentions future process mining research should be about automatically improving processes by changing underlying process models. The first Hashmi paper compares six Compliance Modeling Frameworks (CMFs). There are two pointers to future research directions. 1) Studying the formal semantics of the norms modeling languages. 2) Studying the useability of the norms modeling constructs in practice. The second Hashmi paper is a SLR where 79 papers were included in the study. The study provides a comprehensive overview of the attributes of compliance in BPM. There is a general direction for future research given: to improve modeling languages to take into account all compliance requirements.
The article by van der Aa et al. is about the possible divergence of process descriptions and graphical process models. A quantitive analysis is performed on 53 real-life model-text pairs. One of the suggested future research directions is to also capture process information in other formats. Among the examples given of such other formats are rules and regulations.

0-4 years ago: the three most recent papers in the set are the papers  and @kirKnowledgeintensiveAdaptiveBusiness2021, @bernardojuniorAgileBusinessProcess2023 and @viriyasitavatBlockchainasaServiceBusinessProcess2023. The Kir paper introduces *agile*BPM, a modeling methodology. The main differentiator is that next to control flow *agile*BPM also captures knowledge, rules and goals. A prototype of the system is compared to other similar systems (ADEPT, SmartPM, Planlets, Go4Flex). The paper doesn't mention future research. The Bernardo paper includes a SLR, interviews and expert consultations. Agile BPM is defined. Future research is suggested to be on practices necessary for empirical application of BPM in organizations. The Viriyasitavat article is a SLR on the use of blockchain technology for business process compliance. The paper argues that blockchain technologies can and are applied for business process compliance. Existing work has a focus on technical implementation of the functionalities of traditional BPM systems. However the use of blockchain technologies also allows for new functionalities. The further research section specifically mentions organizational and legal aspects. 

|  | Year |Article       | Alignment Concepts             | Future Research     |
|--|------|--------------|------------------------------- |---------------------|
| 1| 2011 |Vanderfeesten et al.|ProductData Model         | N                   |
| 2| 2016 |Hadasch et al.   |(Diagram)Descriptive Explanations  | N             |
| 3| 2017 |Van der Aa et al.| Consistency between representation| Y (specific)  |
| 4| 2018 |Van Der Aalst  |Prescriptive Analytics         | Y (general)         |
| 5| 2018 |Hashmi et al.  |Compliance Modeling Frameworks   | Y (specific)      |
| 6| 2018 |Hashmi et al.  |Compliance Modeling Languages    | Y (general)       |
| 7| 2021 |Kir et al.     |Context Awareness / Norm adoption| N                 |
| 8| 2023 |Viriyasitavat et al.  |Blockchain              | Y (general)         |
| 9| 2023 |Bernardo Junior et al.|      -                 | Y (general)         |

: Relevance to research question {#tbl-relevance-to-research-question}

All papers mention approaches for alignment of business processes with regulatory requirements except the Bernardo Junior paper about agile BPM. 

From these 9 papers reviewed, 6 mention future research directions. Two papers mention specific future research topic, for example around "consistency between different process representations" and "the useability of norm modelling constructs".


**Paper digest**
All areas
Any time
Type: Paper
Query: (BPM or 'Business Process Management") and "Regulatory Compliance"

Related Work

[1] Kevin D. Barber; Frank W. Dewhurst; R. L. D. H. Burns; J. B. B. Rogers;  "Business-process Modelling and Simulation for Manufacturing Management: A Practical Way Forward",   BUS. PROCESS. MANAG. J.,  2003.  (IF: 3)
[2] Ying Liu; Samuel Müller; Ke Xu;  "A Static Compliance-checking Framework for Business Process Models",   IBM SYST. J.,  2007.  (IF: 5)
[3] Ulrich Lang; Rudolf Schreiner;  "Managing Business Compliance Using Model-driven Security Management",  2008.
[4] Bruno de Moura Araujo; Eber A. Schmitz; Alexandre L. Correa; Antonio J. Alencar;  "A Method for Validating The Compliance of Business Processes to Business Rules",  2010.  (IF: 3)
[5] Marwane El Kharbili; Qin Ma; Pierre Kelsen; Elke Pulvermüller;  "CoReL: Policy-Based and Model-Driven Regulatory Compliance Management",   2011 IEEE 15TH INTERNATIONAL ENTERPRISE DISTRIBUTED OBJECT ...,  2011.  (IF: 3)
[6] Guido Boella; Marijn Janssen; Joris Hulstijn; Llio Humphreys; Leon van der Torre;  "Managing Legal Interpretation in Regulatory Compliance",  2013.  (IF: 3)
[7] Amal Elgammal; Tom Butler;  "Towards A Framework for Semantically-Enabled Compliance Management in Financial Services",  2014.  (IF: 3)
[8] Shazia Wasim Sadiq; Guido Governatori;  "Managing Regulatory Compliance in Business Processes",  2015.  (IF: 4)
[9] Patrick Delfmann; Michael Hübers;  "Towards Supporting Business Process Compliance Checking with Compliance Pattern Catalogues - A Financial Industry Case Study",   ENTERP. MODEL. INF. SYST. ARCHIT. INT. J. CONCEPT. MODEL.,  2015.  (IF: 3)
[10] Mustafa Hashmi; Guido Governatori; Moe Thandar Wynn;  "Normative Requirements for Regulatory Compliance: An Abstract Formal Framework",   INFORMATION SYSTEMS FRONTIERS,  2016.  (IF: 3)


Summary of the Related Work

Business process modelling (BPM) and business‐process simulation (BPS) help to facilitate process thinking. (Barber et. al., 2003) suggest a practical way forward until hardware and software limitations are overcome.   As enterprises increasingly use business process management systems to automate their business processes, technologies to automatically check the compliance of process models against compliance rules are becoming important. (Liu et. al., 2007) present a method to improve the reliability and minimize the risk of failure of business process management systems from a compliance perspective.   This is because, especially with regulatory compliance, both business and government have to expect large financial and reputational losses if compliance cannot be ensured and demonstrated. (Lang et. al., 2008) illustrate the theory behind Model Driven Security for compliance, provide an improved and extended architecture, as well as a case study in the healthcare industry using the OpenPMF 2.0 technology.   Regulatory compliance of business operations and practices is increasingly becoming an area of great concern for management, costing tens of billions of dollars in compliance actions a year. (Araujo et. al., 2010) present a method for validating business processes with respect to the business rules.   In the discipline of business process management in particular, compliance is considered as an important driver of the efficiency, reliability and market value of companies. For this purpose (Kharbili et. al., 2011) contribute CoReL, a domain-specific modeling language for representing compliance requirements that has a graphical concrete syntax.   Legal Knowledge Management systems that combine repositories of legislation with legal ontologies can support the work of in-house compliance managers. (Boella et. al., 2013) extend the Legal Knowledge Management system Eunomos to deal with alternative interpretations of norms connecting it with Business Process Management systems.   (Elgammal et. al., 2014) propose a semantically-enabled compliance management framework. In the heart of the framework is an integrated semantic repository incorporating regulatory, business and compliance knowledge; i.e., CMKB.   (Sadiq et. al., 2015) present an overarching methodology for aligning business and control objectives. The chapter concludes with a discussion on the role of BPM as a driver for regulatory compliance and a presentation of open questions and challenges.   In the business process compliance management literature, (Delfmann et. al., 2015) find an abundance of approaches supporting business process compliance checking. With this objective of (Delfmann et. al., 2015) at making a step towards comprehensive catalogues of compliance rules that can be used as input for business process compliance checking approaches.   By definition, regulatory rules (in legal context called norms) intend to achieve specific behaviour from business processes, and might be relevant to the whole or part of a business process. (Hashmi et. al., 2016) present an abstract framework consisting of a list of norms and a generic compliance checking approach on the idea of (possible) execution of processes.



<!-- 
Businesses can identify relevant regulatory requirements through a comprehensive approach that involves understanding and analyzing various sources of compliance mandates. These sources include legislation and regulatory bodies (e.g., Sarbanes-Oxley and Basel II), standards and codes of practices (e.g., ISO 9001), and business partner contracts.

regulatory compliance and legal compliance

legislation and regulatory bodies

....

Goedertier and Vanthienen

Three articles are about the use of blockchain for BPM @anjumBlockchainStandardsCompliance2017 and @mendlingBlockchainsBusinessProcess2018 and @viriyasitavatBlockchainasaServiceBusinessProcess2023. The latter is a systematic literature about blockchain technology applied to servicing business processes. Chapter V is about business process compliance. Chapter VI details various applications such as the use of smart contracts as a Service for Controls of business processes (p7). This concept is of interest to this review (RD1).

Logic ()

Languages like BPMN-Q and LegalML

Semantics /textual + @vanderaaComparingTextualDescriptions2017 and @yipSemanticallyEnabledApplications2012 and @kharbiliFrameworkSemanticBusiness2008

@hashmiAreWeDone2018

From Science Direct @holzmuller-laueImprovedComplianceBPMDriven2014, 

Several publications (1,2,3) mention both compliance and conformance of business processes.
Compliance is externally imposed and legally binding, focusing on meeting regulatory and legal requirements (source). Conformance is about meeting standards and specifications to ensure quality and reliability, which can be a voluntary process driven by internal or external standards (source). In the context of this literature we are interested in compliance. Compliance requires translation of external rules to internal business rules. For conformance the translation

Does the business process exist outside of the organization. xxx and yyy reference a category of business processes they label cross-organizational business processes. As the name implies ...
On one hand of the spectrum there is a desire for governmental bodies to take into account (semi-)automated execution by companies. On the other side of the spectrum there is a "plea for instruments assessing the impact of policies on organizations prior to implementation" @gongPolicyImplementationBusiness2012. In the middle, presumably, is where the efforts are concentrated
-->
<!---
Conformance refers to the act of adhering to a set of standards or requirements. It involves ensuring that a product, service, or system meets the specified expectations and performs as intended. Conformance can be viewed as a proactive approach to quality management, where the focus is on preventing defects and errors from occurring in the first place.

Conformance often involves the use of quality management systems, such as ISO 9001, which provide a framework for organizations to establish and maintain a culture of quality. These systems typically involve a set of procedures and processes that are designed to ensure that products and services consistently meet customer requirements and comply with relevant regulations.

....
-->
