
latex scrlayer-scrpage,


(Business Processes and Regulatory Compliance

## Need for SLR

This SLR is undertaken as a sprelude to further research.

- What are the review’s objectives?
- What sources were searched to identify primary studies? Were there any restrictions?
- What were the inclusion/exclusion criteria and how were they applied? 
- What criteria were used to assess the quality of primary studies? 
- How were quality criteria applied? 
- How were the data extracted from the primary studies? 
- How were the data synthesised? 
- How were differences between studies investigated? 
- How were the data combined? 
- Was it reasonable to combine the studies? 
- Do the conclusions flow from the evidence?

Follow on publications:

Title [@lokinAgileLawMaking2020]

## Definitions

Regulatory Compliance

Business Process Management

Agility

** Create Zotero(?) report whereby I get abstract, methodology etc. of paper.

\newpage

## Keyword (from articles)

"Regulatory Compliance"
A Semantic Model Based Framework for Regulatory Reporting Process Management
Author keywords: Events, Process extraction, Regulatory reporting, Semantic technology
Prominence percentile 99.023 (shows the current momentum of a Topic, i.e. very high)


I want to expand the number of SLR to 10 by including SLR's from A-star journals in the BPM/IS field(s).

To demonstrate International Research Collaboration (IRC), "using affiliations listed in publications has become the standard practice" [](https://direct.mit.edu/qss/article/3/3/529/112967/Assessing-the-quality-of-bibliographic-data). I would like to use this to show the affiliations of the authors of the articles included in my literature research.

Concepts mentioned in the article:

- Data quality (DQ) and Data quality assessment (DQA)
- Functional Requirements for Bibliographic Records (FRBR)
- Zotero Data quality dimensions (DQDs)

In the article above DQ is split into:

- Intrinsic Data Quality (4 attributes)
- Contextual Data Quality (5 attributes)
- Representational Data Quality (4 attributes)
- Accessibility Data Quality (2 attributes)

Note: in this study Microsoft Academic Graph (MAG) is one of the four datasources considered. MAG has since been [retired](https://www.microsoft.com/en-us/research/project/microsoft-academic-graph/).

This is a Quarto book. It contains x sprints that shall cumulate in the litreview.

* Include citations count
* Include authors count
* Include affiliations count

Document attributes:

* the number of tables is total{table}
* the number of figures is total{figure}
* the number of references is total{citenum}

* add list of tables
* add list of figures

# Resources

Over [markdown](https://www.arthurperret.fr/)