---
format: 
    pdf:
        papersize: a4
        toc: true 
    html:
        toc: true
latex-output-dir: output
bibliography: MyLibrary.bib
link-citations: true
---
# Selected Abstracts {#appendix-g}

<!-- excluded: conference paper

**WS1 A knowledge-intensive adaptive business process management framework (@kirKnowledgeintensiveAdaptiveBusiness2021)**
Business process management has been the driving force of optimization and operational efficiency for companies until now, but the digitalization era we have been experiencing requires businesses to be agile and responsive as well. In order to be a part of this digital transformation, delivering new levels of automation-fueled agility through digitalization of BPM itself is required. However, the automation of BPM cannot be achieved by solely focusing on process space and classical planning techniques. It requires a holistic approach that also captures the social aspects of the business environment, such as corporate strategies, organization policies, negotiations, and cooperation. For this purpose, we combine BPM, knowledge-intensive systems and intelligent agent technologies, and yield one consolidated intelligent business process management framework, namely agileBPM, that governs the entire BPM life-cycle. Accordingly, agileBPM proposes a modeling methodology to semantically capture the business interests, enterprise environment and process space in accordance with the agent-oriented software engineering paradigm. The proposed agent-based process execution environment provides cognitive capabilities (such as goal-driven planning, norm compliance, knowledge-driven actions, and dynamic cooperation) on top of the developed business models to support knowledge workers' multicriteria decision making tasks. The context awareness and exception handling capabilities of the proposed approach have been presented with experimental studies. Through comparative evaluations, it is shown that agileBPM is the most comprehensive knowledge-intensive process management solution.
-->

**1.WS2 Blockchain-as-a-Service for Business Process Management: Survey and Challenges (@viriyasitavatBlockchainasaServiceBusinessProcess2023)**

Blockchain technology (BCT) has brought a paradigm shift to Business Process Management (BPM). BCT provides a trusted decentralized infrastructure to secure data and process executions using distributed ledgers and smart contract to manage complex business processes. Numerous efforts have been made to exploit BCT in supporting dynamic and trusted collaborations of business processes. This paper aims to understand recent BCT development for its BPM applications and identify the limitations and challenges for further development via a systematic literature review (SLR). It is found that numerous works have reported using BCT as technical solutions to fulfill some traditional BPM functions. This paper is distinguished from existing works, especially several relevant surveys in the sense that (1) the impact of using BCT in BPM is thoroughly explored to identify new constraints and challenges explicitly brought by blockchains; (2) the requirements for Business Process Compliance (BPC) are firstly analyzed in detail. Note that BPC is to assure the adherence of business processes to pre-defined policies, standards, specifications, **regulations**, and laws when business processes are executed. To fill the gaps of BCT applications in these two aspects, Blockchain-as-a-Service (BCaaS) is adopted in business process architecture, and the trends of BCT developments are identified accordingly.

**2.WS3 Blockchain-based business process management (BPM) framework for service composition in industry 4.0 (@viriyasitavatBlockchainasaServiceBusinessProcess2023)**

Business process management (BPM) aims to optimize business processes to achieve better system performance such as higher profit, quicker response, and better services. BPM systems in Industry 4.0 are required to digitize and automate business process workflows and support the transparent interoperations of service vendors. The critical bottleneck to advance BPM systems is the evaluation, verification, and transformation of trustworthiness and digitized assets. Most of BPM systems rely heavily on domain experts or third parties to deal with trustworthiness. In this paper, an automated BPM solution is investigated to select and compose services in open business environment, Blockchain technology (BCT) is explored and proposed to transfer and verify the trustiness of businesses and partners, and a BPM framework is developed to illustrate how BCT can be integrated to support prompt, reliable, and cost-effective evaluation and transferring of Quality of Services in the workflow composition and management.

**3.WS4 BPM perspectives to support ICSs: Exploiting the integration of formal verifications into investment service provision processes (@raucciBPMPerspectivesSupport2020)**

Purpose This paper investigates the criteria for a selective integration, in the multidisciplinary business process management (BPM) areas, between information technologies tools and the company's internal control systems (ICSs) aimed at directing organizational behaviours. Adopting a process-based perspective, the authors propose a formal methodology to increase ICSs aims, related to the segregation of duties (SoDs) models, efficiently and effectively. Design/methodology/approach The authors examine the applicability of formal verifications to validate a banking process of providing investment services, which is mapped through the workflow management system. To mitigate the state explosion problem of formal methods, the authors propose an efficient methodology that has been proved on the SoDs models in the bank ICSs, as a case study. Findings The authors' investigations suggest that in the BPM domain, the banking ICSs aims can benefit from the aforesaid methodologies, originating from the formal methods area, to increase the reliability and correctness in the design, modelling and implementation of the SoDs models. Originality/value The proposed methodology is quite general and can be efficiently applied to large-scale systems in different business contexts or areas of the BPM. Its application to the bank's SoD prevents or detects significant weaknesses, operational risks, excessive risk appetite and other undesirable behaviours in the investment services provision processes. This guarantees that the investment ordered/offered is "suitable and appropriate" with the client's risk profile, especially non-professional, required by the MiFID II Directive.

**4.WS5 Business Process Compliance Management: An Integrated Proactive Approach (@elgammalBusinessProcessCompliance2014)**

Today's enterprises demand a high degree of **compliance** of business processes to meet regulations, such as Sarbanes-Oxley and Basel I-III. To ensure continuous guaranteed compliance, compliance management should be considered during all phases of the business process lifecycle; from the analysis and design to deployment, monitoring and evaluation. This paper introduces an integrated business process compliance management framework that incorporates design-time verification and runtime monitoring approaches. The nutshell of the approach is the Compliance Request Language (CRL), which is a high-level pattern-based language for the abstract specification of compliance requirements. From CRL expressions, formal compliance rules can be automatically generated, thereby eliminating the need for business and compliance experts to learn and use complex low-level formal languages. Formalized compliance rules enable automated approaches to be used for the static verification and dynamic monitoring of business processes. An integrated prototypical tool-suite is developed as a proof-of-concept to help validating the applicability of the approaches, and validated by experiment with two real-life case studies.

**5.WS6 The influence of directive explanations on users' business process compliance performance**

In organizations, individual user’s compliance with business processes is important from a regulatory and efficiency point of view. The restriction of users’ choices by implementing a restrictive information system is a typical approach in many organizations. However, restrictions and mandated compliance may affect employees’ performance negatively. Especially when users need a certain degree of flexibility in completing their work activity. The purpose of this paper is to introduce the concept of directive explanations (DEs). DEs provide context-dependent feedback to users, but do not force users to comply.
Design/methodology/approach
The experimental study used in this paper aims at investigating how DEs influence users’ process compliance. The authors used a laboratory experiment to test the proposed hypotheses. Every participant underwent four trials for which business process compliance was measured. Two trial blocks were used to cluster the four trials. Diagrammatic DEs were provided in one of the trial blocks, while textual DEs were provided in the other. Trial blocks were counterbalanced.
Findings
The results of the experiment show that DEs influence a user’s compliance, but the effect varies for different types of DEs. The authors believe this study is significant as it empirically examines design characteristics of explanations from knowledge-based systems in the context of business processes.
Research limitations/implications
This study is certainly not without limitations. The sample used for this study was drawn from undergraduate information systems management students. The sample is thus not representative of the general population of organizations’ IT users. However, a student sample adequately represents novice IT users, who are not very familiar with a business process. They are particularly suitable to study how users react to first-time contact with a DE.
Practical implications
The findings of this study are important to designers and implementers of systems that guide users to follow business processes. As the authors have illustrated with a real-world scenario, an ERP system’s explanation can lack details on how a user can resolve a blocked activity. In situations in which users bypass restricted systems, DEs can guide them to comply with a business process. Particularly diagrammatic explanations, which depict actors, activities, and constraints for a business process, have been found to increase the probability that users’ behavior is business process compliant. Less time may be needed to resolve a situation, which can result in very efficient user-system cooperation.
Originality/value
This study makes several important contributions to research on explanations, which are provided by knowledge-based systems. First, the authors conceptualized, designed, and investigated a novel type of explanations, namely, DEs. The results of this study show how dramatic the difference in process compliance performance is when exposed to certain types of DEs (in one group from 57 percent on the initial trial to 82 percent on the fourth trial). This insight is important to derive design guidelines for DE, particularly when multimedia material is used.

<!-- excluded: conference paper
**WS7 Improved Compliance by BPM-Driven Workflow Automation (@holzmuller-laueImprovedComplianceBPMDriven2014)**

Using methods and technologies of business process management (BPM) for the laboratory automation has important benefits (i.e., the agility of high-level automation processes, rapid interdisciplinary prototyping and implementation of laboratory tasks and procedures, and efficient real-time process documentation). A principal goal of the model-driven development is the improved transparency of processes and the alignment of process diagrams and technical code. First experiences of using the business process model and notation (BPMN) show that easy-to-read graphical process models can achieve and provide standardization of laboratory workflows. The model-based development allows one to change processes quickly and an easy adaption to changing requirements. The process models are able to host work procedures and their scheduling in compliance with predefined guidelines and policies. Finally, the process-controlled documentation of complex workflow results addresses modern laboratory needs of quality assurance. BPMN 2.0 as an automation language to control every kind of activity or subprocess is directed to complete workflows in end-to-end relationships. BPMN is applicable as a system-independent and cross-disciplinary graphical language to document all methods in laboratories (i.e., screening procedures or analytical processes). That means, with the BPM standard, a communication method of sharing process knowledge of laboratories is also available.

**WS8 Regulatory Instability, Business Process Management Technology, and BPM Skill Configurations (@DBLP:conf/bpm/LohmannM19)**

This paper investigates how firms configure their business process management efforts in different industries. We generate a business process management (BPM) skills taxonomy through the computational linguistic analysis of job ads from Monster.com . We apply the taxonomy to LinkedIn.com resumes of professionals employed at retailer Walmart, pharmaceutical company Pfizer, and investment bank Goldman Sachs. We find that Walmart and Pfizer distribute change- and operations-related BPM skills among the same roles whereas Goldman Sachs distributes both kinds of skills among more separate roles. This separation reflects a trilateral configuration where line managers and analysts focus on operational BPM tasks related to running processes while change-related tasks are covered by project managers. At Walmart and Pfizer the tasks of the BPM project manager are shared among managers and analysts, reflecting a bilateral configuration. Comparing each firm's **regulatory** environments and BPM technology capabilities, we conjecture that the organizational configuration pattern is influenced by a firm's ability to reliably automate business processes, since this affects how much attention line managers and analysts have to spend on monitoring processes and on reconciling issues and exceptions. This attention could otherwise be spent on regulatory-imposed process change efforts. This configural logic suggests a reconfiguration of BPM professionals towards a bilateral configuration when an organization transforms its business with digital technology, because the focus of such efforts includes process and decision automation.

**WS9 SEMPA - A Semantic Business Process Management Approach for the Planning of Process Models (@heinrichSEMPAAnsatzSemantischen2008)**

Full text article not accesible (wirtschaftsinformatick) & German

Currently process modeling is mostly done manually. Therefore, the initial design of process models as well as changes to process models which are frequently necessary to react to new market developments or new **regulations** are time-consuming tasks. In this paper we introduce SEMPA, an approach for the partly automatic planning of process models. Using ontologies to semantically describe actions - as envisioned in Semantic Business Process Management -, a process model for a specified problem setting can be created automatically. In comparison to existing planning algorithms our approach creates process models including control structures and is able to cope with complex and numerical input and output parameters of actions. The prototypical implementation as well as an example taken from the financial services domain illustrate the practical benefit of our approach.
-->

<!-- 6 -->
**6.WS10 A knowledge-intensive adaptive business process management framework? (@kirKnowledgeintensiveAdaptiveBusiness2021)**

Business process management has been the driving force of optimization and operational efficiency for companies until now, but the digitalization era we have been experiencing requires businesses to be agile and responsive as well. In order to be a part of this digital transformation, delivering new levels of automation-fueled agility through digitalization of BPM itself is required. However, the automation of BPM cannot be achieved by solely focusing on process space and classical planning techniques. It requires a holistic approach that also captures the social aspects of the business environment, such as corporate strategies, organization policies, negotiations, and cooperation. For this purpose, we combine BPM, knowledge-intensive systems and intelligent agent technologies, and yield one consolidated intelligent business process management framework, namely agileBPM, that governs the entire BPM life-cycle. Accordingly, agileBPM proposes a modeling methodology to semantically capture the business interests, enterprise environment and process space in accordance with the agent-oriented software engineering paradigm. The proposed agent-based process execution environment provides cognitive capabilities (such as goal-driven planning, norm compliance, knowledge-driven actions, and dynamic cooperation) on top of the developed business models to support knowledge workers’ multicriteria decision making tasks. The context awareness and exception handling capabilities of the proposed approach have been presented with experimental studies. Through comparative evaluations, it is shown that agileBPM is the most comprehensive knowledge-intensive process management solution.

<!-- excluded: conference paper
**WS11 The influence of BPM-supportive culture and individual process orientation on process conformance (@benraadInfluenceBPMsupportiveCulture2022)**

Purpose Organizations rely on their business processes to achieve their business objectives and ensure **compliance** with relevant laws and regulations. Hence, conformance to process specifications is essential to remain compliant. Various factors influence an organization's ability to operate in conformance to its process specifications. This study investigates the influence of business process management (BPM**-supportive culture and individual process orientation on process conformance. Design/methodology/approach A construct was created for perceived process conformance and two constructs were selected from literature to represent BPM-supportive culture and individual process orientation. A survey was conducted with 178 employees of a global enterprise, hypotheses were formulated, and a statistical model was constructed and validated. Findings Results pinpoint the key role of the BPM-supportive culture in influencing both individual process orientation and conformance. Individual process orientation is also found to have a significant influence on process conformance. The findings provide additional evidence for the significance of human-related aspects of BPM in achieving BPM success. Originality/value The contributions of this paper help better understand how soft factors of BPM contribute to employees' process conformance drawing on and relating concepts of BPM and organizational routines.

**WS12 Using Business Process Compliance Approaches for Compliance Management with Regard to Digitization: Evidence from a Systematic Literature Review (@DBLP:conf/bpm/SackmannKS18)**

Business Process Compliance (BPC) means ensuring that business processes are in accordance with relevant compliance requirements. Thus, BPC is an essential part of both business process management (BPM) and compliance management (CM). Digitization has also been referred to as a "digital revolution" that describes a technological change that has extended to many organizational areas and tasks, including compliance. Current efforts to digitize, e.g., by realizing cyber-physical systems, rely on the automation and interoperability of systems. In order for CM not to hamper these efforts, it becomes an increasingly relevant issue to digitize compliance as well.  
The managerial perspective of compliance comprises several phases, which together represent a CM life-cycle. Efforts to digitize compliance require bundling interoperable BPC technologies, methods, and tools supporting this life-cycle in a consolidated manner. Several approaches addressing the field of BPC have already been developed and explored. Based on a systematic literature review, we examined these approaches in terms of their suitability for supporting the CM life-cycle phases in support of the digitization of compliance.  
The results of our literature review show which CM life-cycle phases are supported by BPC approaches and which phases are the focus of research. Moreover, the results show that a purely sequential clustering, as specified in a CM life-cycle, is not always suitable for the bundling of BPC approaches in support of the digitization of compliance. Consequently, we propose a novel, task-oriented clustering of BPC approaches that is particularly oriented toward interoperability.

**WS13 The Biggest Business Process Management Problems of Our Time (@beerepootBiggestBusinessProcess2021)**

in additional? it doesn't mention cross organizational processes?

It may be tempting for researchers to stick to incremental extensions of their current work to plan future research activities. Yet there is also merit in realizing the grand challenges in one’s field. This paper presents an overview of the nine major research problems for the Business Process Management discipline. These challenges have been collected by an open call to the community, discussed and refined in a workshop setting, and described here in detail, including a motivation why these problems are worth investigating. This overview may serve the purpose of inspiring both novice and advanced scholars who are interested in the radical new ideas for the analysis, design, and management of work processes using information technology.
-->

**7.WOS14 Toward agile Business Process Management: Description of concepts and a proposed definition (@bernardojuniorAgileBusinessProcess2023)**

Business Process Management (BPM) needs to be adjusted quickly and flexibly to cope with the dynamics of the business environment, so the demand for the incorporation of agility has reached BPM. To contribute to the theoretical consolidation of Agile BPM, it is necessary to develop a conceptualization for the term, that is, to describe the essential attributes for its understanding. Communicating the meaning of the concept in reduced words occurs through the definition, so the main objective of this study is to develop a scientific definition for Agile BPM. This study was performed in three phases. First, a systematic literature review was conducted to investigate how the scientific literature has addressed Agile BPM. Next, a deductive analysis was performed to conceptualize Agile BPM. In the third phase, a consultation with experts was conducted to refine the conceptual view and critique a tentative definition, preceded by judges' analysis to consolidate the definition. As a result, the concept of Agile BPM was elaborated, and based on the reduction of this conceptualization, a scientific definition was presented which describes that Agile BPM is “the promotion of BPM in which practitioners stimulate change quickly and flexibly in order to meet organizational demands with compliance and provide a better customer experience”. There is a pioneering spirit in the present study regarding the deliberate conceptualization of Agile BPM, which provides the basis for discussion of the topic, and helps scientific dissemination through a definition, contributing to the development of a theory of Agile BPM.

**8.WOS15 Spreadsheets for business process management Using process mining to deal with "events" rather than "numbers"? (@vanderaalstSpreadsheetsBusinessProcess2018)**

Purpose – Process mining provides a generic collection of techniques to turn event data into valuable insights, improvement ideas, predictions, and recommendations. This paper uses spreadsheets as a metaphor to introduce process mining as an essential tool for data scientists and business analysts. The purpose of this paper is to illustrate that process mining can do with events what spreadsheets can do with numbers. Design/methodology/approach – The paper discusses the main concepts in both spreadsheets and process mining. Using a concrete data set as a running example, the different types of process mining are explained. Where spreadsheets work with numbers, process mining starts from event data with the aim to analyze processes. Findings – Differences and commonalities between spreadsheets and process mining are described. Unlike process mining tools like ProM, spreadsheets programs cannot be used to discover processes, check compliance, analyze bottlenecks, animate event data, and provide operational process support. Pointers to existing process mining tools and their functionality are given. Practical implications – Event logs and operational processes can be found everywhere and process mining techniques are not limited to specific application domains. Comparable to spreadsheet software widely used in finance, production, sales, education, and sports, process mining software can be used in a broad range of organizations. Originality/value – The paper provides an original view on process mining by relating it to the spreadsheets. The value of spreadsheet-like technology tailored toward the analysis of behavior rather than numbers is illustrated by the over 20 commercial process mining tools available today and the growing adoption in a variety of application domains. 

**Keywords** Process mining, Business process management (BPM), Spreadsheets, Data science Paper type Viewpoint

**9.WOS16 BPM perspectives to support ICSs: Exploiting the integration of formal verifications into investment service provision processes (@raucciBPMPerspectivesSupport2020)**

Purpose This paper investigates the criteria for a selective integration, in the multidisciplinary business process management (BPM) areas, between information technologies tools and the company's internal control systems (ICSs) aimed at directing organizational behaviours. Adopting a process-based perspective, the authors propose a formal methodology to increase ICSs aims, related to the segregation of duties (SoDs) models, efficiently and effectively. Design/methodology/approach The authors examine the applicability of formal verifications to validate a banking process of providing investment services, which is mapped through the workflow management system. To mitigate the state explosion problem of formal methods, the authors propose an efficient methodology that has been proved on the SoDs models in the bank ICSs, as a case study. Findings The authors’ investigations suggest that in the BPM domain, the banking ICSs aims can benefit from the aforesaid methodologies, originating from the formal methods area, to increase the reliability and correctness in the design, modelling and implementation of the SoDs models. Originality/value The proposed methodology is quite general and can be efficiently applied to large-scale systems in different business contexts or areas of the BPM. Its application to the bank's SoD prevents or detects significant weaknesses, operational risks, excessive risk appetite and other undesirable behaviours in the investment services provision processes. This guarantees that the investment ordered/offered is “suitable and appropriate” with the client's risk profile, especially non-professional, required by the MiFID II Directive.

**10.WOS17 Improved Compliance by BPM-Driven Workflow Automation (@holzmuller-laueImprovedComplianceBPMDriven2014)**

Using methods and technologies of business process management (BPM) for the laboratory automation has important benefits (i.e., the agility of high-level automation processes, rapid interdisciplinary prototyping and implementation of laboratory tasks and procedures, and efficient real-time process documentation). A principal goal of the model-driven development is the improved transparency of processes and the alignment of process diagrams and technical code. First experiences of using the business process model and notation (BPMN) show that easy-to-read graphical process models can achieve and provide standardization of laboratory workflows. The model-based development allows one to change processes quickly and an easy adaption to changing requirements. The process models are able to host work procedures and their scheduling in compliance with predefined guidelines and policies. Finally, the process-controlled documentation of complex workflow results addresses modern laboratory needs of quality assurance. BPMN 2.0 as an automation language to control every kind of activity or subprocess is directed to complete workflows in end-to-end relationships. BPMN is applicable as a system-independent and cross-disciplinary graphical language to document all methods in laboratories (i.e., screening procedures or analytical processes). That means, with the BPM standard, a communication method of sharing process knowledge of laboratories is also available.

**11.SD2 Business Process Reengineering of emergency management procedures: A case study (@bevilacquaBusinessProcessReengineering2012)**

The production and storage of dangerous substances in an industrial establishment creates risks for man, environment and properties in the surrounding area. Safety **regulations** require the establishment of a preventive information campaign regarding industrial risks and self-defence measures to adopt in an emergency situation. In the case of a major accident, people must be promptly made aware of the appropriate self-defence actions and behaviours to adopt. This strategic activity can reduce the panic effect, make citizens more cooperative and guarantee the effectiveness of any emergency plan. In this paper, the information chain is studied as an industrial process modelled by the IDEFO language. Through this method, each link in the chain has been deeply analysed. For each function of the process, the inputs, outputs and necessary controls and resources have been identified. Starting from a clear view of the current state, the process of re-engineering has been implemented to minimise or eliminate downtime, deficiencies and illnesses and, thus, consequent time losses. The main contribution of the IDEFO application in emergency management is to provide a clear view of the whole system, a communication system between emergency actors, a rich information source and a structured base for the re-engineering process.

<!-- excluded: bookchapter and conference papers
**SD1 A knowledge-intensive adaptive business process management framework (@kirKnowledgeintensiveAdaptiveBusiness2021)**

Business process management has been the driving force of optimization and operational efficiency for companies until now, but the digitalization era we have been experiencing requires businesses to be agile and responsive as well. In order to be a part of this digital transformation, delivering new levels of automation-fueled agility through digitalization of BPM itself is required. However, the automation of BPM cannot be achieved by solely focusing on process space and classical planning techniques. It requires a holistic approach that also captures the social aspects of the business environment, such as corporate strategies, organization policies, negotiations, and cooperation. For this purpose, we combine BPM, knowledge-intensive systems and intelligent agent technologies, and yield one consolidated intelligent business process management framework, namely agileBPM, that governs the entire BPM life-cycle. Accordingly, agileBPM proposes a modeling methodology to semantically capture the business interests, enterprise environment and process space in accordance with the agent-oriented software engineering paradigm. The proposed agent-based process execution environment provides cognitive capabilities (such as goal-driven planning, norm **compliance**, knowledge-driven actions, and dynamic cooperation) on top of the developed business models to support knowledge workers’ multi-criteria decision making tasks. The context awareness and exception handling capabilities of the proposed approach have been presented with experimental studies. Through comparative evaluations, it is shown that agileBPM is the most comprehensive knowledge-intensive process management solution.

**SD2 From policy implementation to business process management: Principles for creating flexibility and agility (@gongPolicyImplementationBusiness2012)**

Organizations are required to comply with changes in legislation and policy. Yet the implementation of new legislation is often expensive, can have long lead times and is prone to failure. The existing situation significantly constrains policy-making. To improve this, policy makers and policy executors are searching for ways to achieve higher levels of flexibility and agility in their business process management systems. Flexibility is the ability to react to changes and agility is the speed in responding to variety and change. Both flexibility and agility are multi-dimensional concepts.  
This paper presents principles for creating flexibility and agility when implementing new or revised policies into business processes. These principles include: 1) defining and using business services, 2) integrating and orchestrating business services through the use of events, 3) separating process, knowledge and resources and 4) implementing policy in an integrated manner. Business services are components encapsulating business functions and having clear responsibilities and accountabilities. The case study shows that these forms of flexibility and agility can help to implement policies more quickly and cost effectively. An organization's resources and level of flexibility and agility determines what laws can be implemented within a certain time. The improvement of flexibility and agility requires innovations on all levels: infrastructure, business process and organization. The level of flexibility and agility should always be measured by a combination of measures. We make plea for instruments assessing the impact of policies on organizations prior to implementation.

**SD3 Improved Compliance by BPM-Driven Workflow Automation (@holzmuller-laueImprovedComplianceBPMDriven2014)**

Using methods and technologies of business process management (BPM) for the laboratory automation has important benefits (i.e., the agility of high-level automation processes, rapid interdisciplinary prototyping and implementation of laboratory tasks and procedures, and efficient real-time process documentation). A principal goal of the model-driven development is the improved transparency of processes and the alignment of process diagrams and technical code. First experiences of using the business process model and notation (BPMN) show that easy-to-read graphical process models can achieve and provide standardization of laboratory workflows. The model-based development allows one to change processes quickly and an easy adaption to changing requirements. The process models are able to host work procedures and their scheduling in compliance with predefined guidelines and policies. Finally, the process-controlled documentation of complex workflow results addresses modern laboratory needs of quality assurance. BPMN 2.0 as an automation language to control every kind of activity or subprocess is directed to complete workflows in end-to-end relationships. BPMN is applicable as a system-independent and cross-disciplinary graphical language to document all methods in laboratories (i.e., screening procedures or analytical processes). That means, with the BPM standard, a communication method of sharing process knowledge of laboratories is also available.

**SD4 Improving Telemedicine Processes Via BPM (@ilahiImprovingTelemedicineProcesses2013)**

BPM is an emerging theme that plays an important role in the global market of Business Processes. An efficient Management of Business Processes is able to ensure the requested development and competitiveness. A company which will be based on Business Process Management will provide a climate favoring the cooperation of its employees; they will be engaged in realizing well-defined tasks leading to an effective achievement of its objectives.  
Although telemedicine is an emerging successful field, it still suffers from problems of understanding, lack of techniques and legal texts and huge costs, and is still rarely used especially in Tunisia. Hence, the importance of process modeling and discovery of relevant technological means facilitating their use and automation. In this work, we designed, developed and tested a solution deploying Teleconsulting Process and remote diagnosis through a BPMS (Business Process Management System) that ensures their automation based on BPMN 2.0 models.
-->

**12.arXiv1 Blockchains for Business Process Management - Challenges and Opportunities (@mendlingBlockchainsBusinessProcess2018)**

<!-- Why didn't this article show up in the arXiv search? Did it show up in WoS? "compliance" and "regulations" only in the full text -->

Blockchain technology offers a sizable promise to rethink the way inter-organizational business processes are managed because of its potential to realize execution without a central party serving as a single point of trust (and failure). To stimulate research on this promise and the limits thereof, in this paper we outline the challenges and opportunities of blockchain for Business Process Management (BPM). We first reflect how blockchains could be used in the context of the established BPM lifecycle and second how they might become relevant beyond. We conclude our discourse with a summary of seven research directions for investigating the application of blockchain technology in the context of BPM.

**13.arXiv2 Recognizing and Splitting Conditional Sentences for Automation of Business Processes Management (@voRecognizingSplittingConditional2021)**

Business Process Management (BPM) is the discipline which is responsible for management of discovering, analyzing, redesigning, monitoring, and controlling business processes. One of the most crucial tasks of BPM is discovering and modelling business processes from text documents. In this paper, we present our system that resolves an end-to-end problem consisting of 1) recognizing conditional sentences from technical documents, 2) finding boundaries to extract conditional and resultant clauses from each conditional sentence, and 3) categorizing resultant clause as Action or Consequence which later helps to generate new steps in our business process model automatically. We created a new dataset and three models solve this problem. Our best model achieved very promising results of 83.82, 87.84, and 85.75 for Precision, Recall, and F1, respectively, for extracting Condition, Action, and Consequence clauses using Exact Match metric.

**14.dblp1 A compliance management framework for business process models (@DBLP:phd/de/Awad2010)**

Companies develop process models to explicitly describe their business operations. In the same time, business operations, business processes, must adhere to various types of compliance requirements. **Regulations**, e.g., Sarbanes Oxley Act of 2002, internal policies, best practices are just a few sources of compliance requirements. In some cases, non-adherence to compliance requirements makes the organization subject to legal punishment. In other cases, non-adherence to compliance leads to loss of competitive advantage and thus loss of market share. Unlike the classical domain-independent behavioral correctness of business processes, compliance requirements are domain-specific. Moreover, compliance requirements change over time. New requirements might appear due to change in laws and adoption of new policies. Compliance requirements are offered or enforced by different entities that have different objectives behind these requirements. Finally, compliance requirements might affect different aspects of business processes, e.g., control flow and data flow. As a result, it is infeasible to hard-code compliance checks in tools. Rather, a repeatable process of modeling compliance rules and checking them against business processes automatically is needed. This thesis provides a formal approach to support process design-time compliance checking. Using visual patterns, it is possible to model compliance requirements concerning control flow, data flow and conditional flow rules. Each pattern is mapped into a temporal logic formula. The thesis addresses the problem of consistency checking among various compliance requirements, as they might stem from divergent sources. Also, the thesis contributes to automatically check compliance requirements against process models using model checking. We show that extra domain knowledge, other than expressed in compliance rules, is needed to reach correct decisions. In case of violations, we are able to provide a useful feedback to the user. The feedback is in the form of parts of the process model whose execution causes the violation. In some cases, our approach is capable of providing automated remedy of the violation.

<!-- Sector: Healthcare Citation: count (date)
**dblp2 Business Process Modelling in Healthcare and Compliance Management: A Logical Framework (@amanteaBusinessProcessModelling2022)**

This work describes a methodological approach to investigate Compliance Management in healthcare based on a BPM perspective, exploring an application in an innovative hospital service. Firstly, we present a business process analysis by modeling the process with the adoption of a standard language. Secondly, we encode a set of rules in LegalRuleML, an XML formalism designed to be a standard for representing the semantic and logical content of legal documents. The rules represent some provisions of the General Data Protection Regulation (GDPR) that are involved in the health process analyzed. Moreover, in order to perform the **regulatory** compliance check automatically, we converted the set of rules into Defeasible Deontic Logic format (DDL), readable by the Regorous compliance checker developed at CSIRO. Overall, the paper shows a methodology to automate regulatory compliance checking of a real hos- pital process with actual regulations and norms. The codes in the LegalRuleML and DDL formats used in the work are available online1.
-->

**15.dblp3 Comparative Analysis of Business Process Modelling Tools for Compliance Management Support (@DBLP:journals/rigaacs/KoncevicsPGDBA17)**

The paper presents results of the comparative analysis of business process modelling tools for supporting automated compliance management in organisations. By **compliance** in the paper we mean compliance to legislation, **regulations** of municipalities, external regulatory requirements and also internal organisational policies. The goal of the research is (1) to identify main attributes of business process modelling tools relevant in compliance management, and (2) to use the identified attributes for analysis of the tools to better understand the scope of their capability to support compliance management. The attributes of the tools have been derived from the related research. The analysis of the tools has been performed by installing each tool and evaluating it against a set of the identified attributes. The obtained results are useful in choosing the tools for compliance management in general and for open source solutions to develop new compliance management tools in particular.

**16.dblp4 Norms modeling constructs of business process compliance management frameworks: a conceptual evaluation (@DBLP:journals/ail/HashmiG18)**

The effectiveness of a **compliance** management framework (CMF) can be guaranteed only if the framework is based on sound conceptual and formal foundations. In particular, the formal language used in the CMF is able to expressively represent the specifications of normative requirements (hereafter, norms) that impose constraints on various activities of a business process. However, if the language used lacks expressiveness and the modelling constructs proposed in the CMF are not able to properly represent different types of norms, it can significantly impede the reliability of the compliance results produced by the CMF. This paper investigates whether existing CMFs are able to provide reasoning and modeling support for various types of normative requirements by evaluating the conceptual foundations of the modeling constructs that existing CMFs use to represent a specific type of norm. The evaluation results portray somewhat a bleak picture of the state-of-the-affairs when it comes to represent norms as none of the existing CMFs is able to provide a comprehensive reasoning and modeling support. Also, it points to the shortcomings of the CMFs and emphasises exigent need of new modeling languages with sound theoretical and formal foundations for representing legal norms.

**17.aa1 Evaluation of Compliance Rule Languages for Modelling Regulatory Compliance Requirements (@zasadaEvaluationComplianceRule2023)**

Compliance in business processes has become a fundamental requirement given the constant rise in regulatory requirements and competitive pressures that have emerged in recent decades. While in other areas of business process modelling and execution, considerable progress towards automation has been made (e.g., process discovery, executable process models), the interpretation and implementation of compliance requirements is still a highly complex task requiring human effort and time. To increase the level of “mechanization” when implementing **regulations** in business processes, compliance research seeks to formalize compliance requirements. Formal representations of compliance requirements should, then, be leveraged to design correct process models and, ideally, would also serve for the automated detection of violations. To formally specify compliance requirements, however, multiple process perspectives, such as control ﬂow, data, time and resources, have to be considered. This leads to the challenge of representing such complex constraints which affect different process perspectives. To this end, current approaches in business process compliance make use of a varied set of languages. However, every approach has been devised based on different assumptions and motivating scenarios. In addition, these languages and their presentation usually abstract from real-world requirements which often would imply introducing a substantial amount of domain knowledge and interpretation, thus hampering the evaluation of their expressiveness. This is a serious problem, since comparisons of different formal languages based on real-world compliance requirements are lacking, meaning that users of such languages are not able to make informed decisions about which language to choose. To close this gap and to establish a uniform evaluation basis, we introduce a running example for evaluating the expressiveness and complexity of compliance rule languages. For language selection, we conducted a literature review. Next, we brieﬂy introduce and demonstrate the languages’ grammars and vocabularies based on the representation of a number of legal requirements. In doing so, we pay attention to semantic subtleties which we evaluate by adopting a normative classiﬁcation framework which differentiates between different deontic assignments. Finally, on top of that, we apply Halstead’s well-known metrics for calculating the relevant characteristics of the different languages in our comparison, such as the volume, difﬁculty and effort for each language. With this, we are ﬁnally able to better understand the lexical complexity of the languages in relation to their expressiveness. In sum, we provide a systematic comparison of different compliance rule languages based on real-world compliance requirements which may inform future users and developers of these languages. Finally, we advocate for a more user-aware development of compliance languages which should consider a trade off between expressiveness, complexity and usability.

**18.aa2 RegelSpraak: a CNL for Executable Tax Rules Specification (@lokinAgileLawMaking2020)**

RegelSpraak is a CNL developed at the Dutch Tax Administration (DTA) over the last decade. Keeping up with frequently changing tax rules poses a formidable challenge to the DTA IT department. RegelSpraak is a central asset in ongoing efforts of the DTA to attune their tax IT systems to automatic execution of tax law. RegelSpraak now is part of the operational process of rule specification and execution. In this practice-oriented paper, we present the history of RegelSpraak, its properties and the context of its use, emphasizing its double functionality as a language readable by non-technical tax experts but also directly interpretable in a software generating setup.

**19.aa3 Are we done with business process compliance: state of the art and challenges ahead (@hashmiAreWeDone2018)**

Literature on business process compliance (BPC) has predominantly focused on the alignment of the regulatory rules with the design, veriﬁcation and validation of business processes. Previously surveys on BPC have been conducted with speciﬁc context in mind; however, the literature on BPC management research is largely sparse and does not accumulate a detailed understanding on existing literature and related issues faced by the domain. This survey provides a holistic view of the literature on existing BPC management approaches, and categories them based on diﬀerent compliance management strategies in the context of formulated research questions. A systematic literature approach is used where search terms pertaining keywords were used to identify literature related to the research questions from scholarly databases. From initially 183 papers, we selected 79 papers related to the themes of this survey published between 2000–2015. The survey results reveal that mostly compliance management approaches center around three distinct categories namely: design-time (28%), run-time (32%) and auditing (10%). Also, organisational and internal control based compliance management frameworks (21%) and hybrid approaches make (9%) of the surveyed approaches. Furthermore, open research challenges and gaps are identiﬁed and discussed with respect to the compliance problem.

**Keywords:** Business processes · Business process compliance · Norms compliance · Normative requirements · Compliance Management Frameworks

**20.aa4 Comparing textual descriptions to process models – The automatic detection of inconsistencies (@vanderaaComparingTextualDescriptions2017)**

Many organizations maintain textual process descriptions alongside graphical process models. The purpose is to make process information accessible to various stakeholders, including those who are not familiar with reading and interpreting the complex execution logic of process models. Despite this merit, there is a clear risk that model and text become misaligned when changes are not applied to both descriptions consistently. For organizations with hundreds of different processes, the effort required to identify and clear up such conﬂicts is considerable. To support organizations in keeping their process descriptions consistent, we present an approach to automatically identify inconsistencies between a process model and a corresponding textual description. Our approach detects cases where the two process representations describe activities in different orders and detect process model activities not contained in the textual description. A quantitative evaluation with 53 real-life model-text pairs demonstrates that our approach accurately identiﬁes inconsistencies between model and text.

**21.aa5 Supporting domain experts to select and configure precise compliance rules (@DBLP:conf/bpm/RamezaniFA13)**

Compliance speciﬁcations concisely describe selected aspects of what a business operation should adhere to. To enable automated techniques for compliance checking, it is important that these requirements are speciﬁed correctly and precisely, describing exactly the behavior intended. Although there are rigorous mathematical formalisms for representing compliance rules, these are often perceived to be difﬁcult to use for business users. Regardless of notation, however, there are often subtle but important details in compliance requirements that need to be considered. The main challenge in compliance checking is to bridge the gap between informal description and a precise speciﬁcation of all requirements. In this paper, we present an approach which aims to facilitate creating and understanding formal compliance requirements by providing conﬁgurable templates that capture these details as options for commonly-required compliance requirements. These options are conﬁgured interactively with end-users, using question trees and natural language. The approach is implemented in the Process Mining Toolkit ProM.

**Keywords:** compliance speciﬁcation, compliance checking, conﬁgurable compliance rules, auditing, question tree

**22.aa6 Product-based workflow support (@vanderfeestenProductbasedWorkflowSupport2011)**

Despite the industrial need for the improvement of information-intensive business processes, few scientiﬁcally grounded approaches exist to support such initiatives. In this paper, we propose a new approach that builds on concepts that are part of a product-oriented view on process optimization. Essentially, this approach allows end users to ﬂexibly decide on the best possible way to create an informational product within the limits that are imposed by regulations and logical dependencies. We argue that this provides various beneﬁts in comparison to earlier work. To support the end user in making sensible decisions, we describe two alternative approaches to provide her with recommendations to this end. We formalize these alternatives and discuss their relative strengths and weaknesses. The feasibility of the overall approach, which we refer to as Product-Based Workﬂow Support, is demonstrated by a workﬂow system realized using ProM and DECLARE.

**23.aa7 Compliance monitoring in business processes: Functionalities, application, and tool-support (@lyComplianceMonitoringBusiness2015)**

In recent years, monitoring the compliance of business processes with relevant regula- tions, constraints, and rules during runtime has evolved as major concern in literature and practice. Monitoring not only refers to continuously observing possible compliance violations, but also includes the ability to provide fine-grained feedback and to predict possible compliance violations in the future. The body of literature on business process compliance is large and approaches specifically addressing process monitoring are hard to identify. Moreover, proper means for the systematic comparison of these approaches are missing. Hence, it is unclear which approaches are suitable for particular scenarios. The goal of this paper is to define a framework for Compliance Monitoring Functionalities (CMF) that enables the systematic comparison of existing and new approaches for monitoring compliance rules over business processes during runtime. To define the scope of the framework, at first, related areas are identified and discussed. The CMFs are harvested based on a systematic literature review and five selected case studies. The appropriateness of the selection of CMFs is demonstrated in two ways: (a) a systematic comparison with pattern-based compliance approaches and (b) a classification of existing compliance monitoring approaches using the CMFs. Moreover, the application of the CMFs is showcased using three existing tools that are applied to two realistic data sets. Overall, the CMF framework provides powerful means to position existing and future compliance monitoring approaches.

<-- Misschien een link naar Zotero en/of een link naar Citedrive -->>