---
abstract: ""
format:
  pdf:
    papersize: a4
    mermaid:
      theme: neutral
    cite-method: citeproc
    toc: true
    lof: true
    lot: true 

link-citations: true

execute:
  echo: false
---

<!--
Examples of SLR

[05/10/2023] Looking in my Zotero library for articles with a title that contains "systematic literature review", the result is 7 hits:

- The first is @kitchenhamGuidelinesPerformingSystematic2007 and there is a duplicate @keeleGuidelinesPerformingSystematic2007.
- Second there are 3 SLR's where Van Looy is co-author (@moreno-montesdeocaSystematicLiteratureReview2015, @prodanovaHowBeneficialSocial2019, @ahmadBusinessProcessManagement2020).
- There is 1 SLR about BPMN extensions (@zarourSystematicLiteratureReview2019)
- Finally, there is one SLR about Open Science (@VICENTESAEZ2018428) which is not relevant to BP4RC.
-->

# Introduction

In the context of the DBA program at Vlerick Business School a literature review is one of two deliverables of year two. The research topic is "BPM for regulatory compliance". The goal of this review is to get an overview of relevant literature and identify topics listed as possibilities for future research. The type of literature review is a systematic literature review (SLR). The SLR has been performed following the steps described in @kitchenhamGuidelinesPerformingSystematic2007.

@sec-research-questions states the main research question, three subquestions and provides for a definition of the central concepts.

@sec-review-plan is about the planning of the research. It describes the databases that were searched, the search terms used, the criteria for selecting articles and how the bibliographic data and the articles have been obtained.  

@sec-review-execution concerns the execution of the research. It describes the studies found, which studies have been selected, how the quality of the studies has been assessed, how the data was collected and a synthesis of the data. 

@sec-review-reporting concerns the reporting of the research. It describes how the results of this study will be shared, limitations of the study and possibilities for further research suggesting possible improvements.