---
title: Review reporting
---
# Review reporting{#sec-review-reporting}

## Dissemination strategy

A subsequent version of this review will be part of the PhD work. The aim is to get three by-products out of this review:

- A poster that explains this literature review process and its results to be presented on a research day.
- A version of the software script that is installable and useable by somebody else.
- An open access publication.

<!--
Workflow management system
Business process management
Legal compliance
Regulatory compliance

https://www.planetcompliance.com/legal-and-regulatory-compliance/

[Compliance](https://thecontentauthority.com/blog/conformance-vs-compliance)
[Conformance](https://thecontentauthority.com/blog/conformance-vs-compliance)

Product Data Model (source)
Product Data Model (different source)
Object centric process mining
-->

## Limitations

The database searches resulted in a set of relevant articles for the subject of this review. Selecting a different set of databases would have resulted in a different set of relevant articles. The selection of databases was made from the databases available to us. We did not consider databases that require additional payment for access.

It is also noted that search results may defer among different databases. If the content of two databases is identical, the same query run against both databases can yield different results. The differences stem, among others, from different search fields, different query languages, different API's and different search engines. Examples of notable differences are:

- for WoS: the search results may differ depending on the subscription that is available to the user.
- for SD: the search results may differ as query's are interpreted based on language heuristics ([source](https://service.elsevier.com/app/answers/detail/a_id/35970/supporthub/sciencedirect/)). Also, SD does not support wildcards.
- for dblp: the *CompleteSearch* engine autocompletes search terms, see @bastTypeLessFind2006.
- for arXiv: wildcards can not be used as the first character of a search term ([source](https://www.arxiv.org/multi?%2Ffind=Search/)). For example "*engineering" will trigger an error message.

To assess the quality of the 21 identified articles a set of 4 indicators has been considered. There are many other indicators which can be used to assess the quality of an article. Changing the number of indicators and/or changing the selection of parameters could alter which full text articles are selected for the review.

## Future research

In follow-on research it maybe interesting to include openAIRE (Open Access Infrastructure for Research in Europe) as a data source. @schummBusinessProcessCompliance2010, p. 11 reference research that has been performed under the 2008-2011 [COMPAS](https://cordis.europa.eu/project/id/215175) research project funded by the EU and coordinated by the Technische Universitaet Wien. More information about the research output of these projects will be available via OpenAIRE. When OpenAIRE will be included as a data source we will also again include Zenodo. Zenodo was created as part of the OpenAIRE initiative.

For reproducibility a future version of this literature review shall have the protocol altered. For commercial databases one and the same query can yield different results if it is run with two different licenses. This has been found to be the case with Web of Science. For the query used in this review the Vlerick Business School license of WoS yielded 42 hits while the Amsterdam University of Applied Sciences license of WoS yield 24 hits (to be included in appendix). It is assumed the average user does not have precise information of the licenses that Academic institutions hold. As such WoS is better not used in the early stages of the search. The protocol could instead dictate the use of open databases, such as OpenAlex, for the early stages of the search. Commercial databases would then be used in a later stage to get abstracts and full texts of selected articles that are not available from open databases.

For quality assessment we have now used a self-constructed indicator (QA4) that has as inputs the number of publications by the first and second author. If further research is conducted it can be considered to replace this indicator with the ubiquitous h-index (@WOS:000615174400014). Also, the fact that only 1 article is from the eligible journals list seems to indicate that either the list needs to be revised. Alternatively a different indicator, such as the journal impact factor, can be a substitute quality indicator.

Finally, where it relates to compliance checks, in the literature there is a divide between "design time" and "run time". As the RQ of this research refers to \fbox{compliance by design}, future research may have more of different search terms to also filter research about "design time" compliance checking.

<!--
Did we miss searching for "compliance by design"? Did we miss searching for "inter organizational processes"?  
In practice the term "workflow management system" is used in financial institutions (source: Mark Muyres).


\newpage

**Search Strings Used**


Web of Science:

(TI=("business process" management or BPM) AND (AB=(compliance) OR KP=(compliance))) OR (TI=("business process" management or BPM) AND (AB=(regulat*) OR KP=(regulat*))) OR (TI=("business process *engineering") AND (AB=(compliance) OR KP=(compliance))) OR (TI=("business process *engineering") AND (AB=(regulat*) OR KP=(regulat*)))

DBLP:
- "business process management" compliance
- "business process management" regulat*
- "business process *engineering" compliance
- "business process \*engineering" and regulat*

ScienceDirect:
title="business process management" and tka=compliance or regulation or regulatory or engineering or reengineering or design

Zenodo:  
+title:"business process management" +regulat* OR compliance +resource_type.type:publication

\newpage
-->