---
execute:
  echo: false
jupyter: python3
---
# Quality Criteria {#appendix-f}

\fontsize{9}{10}\selectfont

**Indicator QA3**

The table shows the inputs for calculating the QA3-score. The score is 1 if the outcome of the calculation is larger than or equal to 5, otherwise it is 0. The calculation is: cited/year = number of citations / (2024 - Publication Year).

**Indicator QA4**

The table shows the inputs for calculating the QA4-score. The score is 1 if the outcome of the calculation is larger than or equal to 100, otherwise it is 0. The columns 'First Author' and 'Second Author' hold the number of articles by these authors on google Scholar.

```{python}
#| label: tbl-qa
#| tbl-cap: "Calculation of the QA3-score and QA4-score"

from IPython.display import Markdown
from tabulate import tabulate
from lib.my_excel_lib import get_tables
from lib.my_custom_lib import xls2md

tables = get_tables('tables/slr_logbook.xlsx')

Markdown(tabulate(
  xls2md(tables['criteria_3_4']),
  headers=['Seq','Id','Citations','Year','Cited/Year','QA3-Score','First Author','Second Author','Total Articles','QA4-Score'],
  missingval="",
  maxcolwidths=[2, 8, 5, 5, 5, 5, 5, 5, 5],
  showindex=False,
  colalign=('left','left','right','center','right','center','right','right','right')))
```

Meaning of the column names:  
- Citations : the number of citations on google scholar  
- Year : Year of Publication  
- First author : the number of publications by the first author on google scholar  
- Second author : the number of publications by the second author on google scholar  

\fontsize{11}{12}\selectfont