---
abstract: ""
format:
  pdf:
    papersize: a4
    mermaid:
      theme: neutral
    cite-method: citeproc
    toc: true
    lof: true
    lot: true 

link-citations: true

execute:
  echo: false
---

<!--
Examples of SLR

[05/10/2023] Looking in my Zotero library for articles with a title that contains "systematic literature review", the result is 7 hits:

- The first is @kitchenhamGuidelinesPerformingSystematic2007 and there is a duplicate @keeleGuidelinesPerformingSystematic2007.
- Second there are 3 SLR's where Van Looy is co-author (@moreno-montesdeocaSystematicLiteratureReview2015, @prodanovaHowBeneficialSocial2019, @ahmadBusinessProcessManagement2020).
- There is 1 SLR about BPMN extensions (@zarourSystematicLiteratureReview2019)
- Finally, there is one SLR about Open Science (@VICENTESAEZ2018428) which is not relevant to BP4RC.
-->

# Introduction

In the context of the DBA program at Vlerick Business School a literature review is one of two deliverables of year two. The research topic is "BPM for regulatory compliance". The goal of this review is to get an overview of relevant literature and identify topics listed as possibilities for future research. The type of literature review is a systematic literature review (SLR). The SLR has been performed following the steps described in @kitchenhamGuidelinesPerformingSystematic2007.

@sec-research-questions states the main research question, three subquestions and provides for a definition of the central concepts.

@sec-review-plan is about the planning of the research. It describes the databases that were searched, the search terms used, the criteria for selecting articles and how the bibliographic data and the articles have been obtained.  

@sec-review-execution concerns the exection of the research. It describes the studies found, which studies have been selected, how the quality of the studies has been assessed, how the data was collected and a synthesis of the data. 

@sec-review-reporting concerns the reporting of the research. It describes how the results of this study will be shared, limitations of the study and possibilities for further research suggesting possible improvements.

# Research question(s){#sec-research-questions}

The research question (RQ) and the three supporting sub-questions (SQ) that are addressed in this literature review are:

RQ: What are approaches for aligning business processes with regulatory requirements to achieve regulatory compliance by design?

SQ1: How can businesses identify relevant regulatory requirements? 

SQ2: How can businesses analyze which business processes are affected by changes in regulatory requirements?  

SQ3: How can businesses integrate compliance requirements into business process design?  

<!--
SQ-4: How can businesses ensure compliance throughout the lifecycle of the impacted business processes? Comment: taken out as answering this sub-question does not help answering the main research question.
-->

The focus of this review is specifically the first question (RQ). The following is the research question repeated whereby the central terms and and concepts in this review are boxed: What are approaches for aligning \fbox{business processes} with \fbox{regulatory requirements} to achieve regulatory \fbox{compliance by design}?  
  
A definition of the three central concepts:

Business process management (BPM) is a defined as all activities performed by businesses to discover, model, automate, analyze, measure, improve and optimize business processes (@liuStaticCompliancecheckingFramework2007). A business process coordinates the behavior of people, systems, information and things to produce business outcomes in support of a business strategy. Processes can be structured and repeatable, or unstructured and variable.

Regulatory compliance is defined as ensuring that business processes, operations, and practices are in accordance with a prescribed and/or agreed set of norms. These compliance requirements may stem from legislature and regulatory bodies (e.g., Sarbanes-Oxley, Basel II, HIPAA), standards and codes of practice (e.g., SCOR, ISO9000), and also business partner contracts (@hashmiEvaluatingBusinessProcess2015).

Compliance by design refers to approaches and methodologies where compliance requirements are integrated into business process models (@sadiqManagingRegulatoryCompliance2010) and enterprise applications from the very beginning. This concept emphasizes embedding compliance within the fabric of business practices (@lohmannComplianceDesignArtifactcentric2013) rather than treating it as a separate or after-the-fact activity.

# Review plan{#sec-review-plan}

## Resources to be searched

An initial set of databases was selected to perform the literature search on. Both commercial and open access databases have been selected. A description for these databases in included in @tbl-databases.

1. Web of Science (WoS), Publisher: [Clarivate](https://www-webofscience-com)
1. ScienceDirect (SD), Publisher: [Elsevier](https://www-sciencedirect-com)
1. SSNR, Publisher: [Elsevier](https://www.ssrn.com/)
1. arXiv, Publisher: [cs](https://arxiv.org/search/cs)
1. dblp, Publisher: [dblp](https://dblp.org/)
1. Zenodo, Publisher: [Zenodo](https://zenodo.org)

As a test we performed some initial searches. The results of the initial searches was reviewed. SSNR and Zenodo yielded few results as compared to the other databases. The selection of databases was reduced to WoS, SD, SSNR, ArXiv and dblp.

## Search terms used{#sec-search-terms-used}

The initial search terms have been formulated as follows:

1. ("business process management" or BPM) and "regulatory compliance"
2. ("business process management" or BPM) and "legal compliance"
3. ("business process management" or BPM) and "compliance"
4. "business process management" and ("regulation" or "regulatory")
5. "business process *engineering" and "compliance"
6. "business process *engineering" and ("regulation" or "regulatory")

Here too a test has been performed using the search terms. It was found that the combination of "business process management" with "regulatory compliance" or "legal compliance" yieded few results. Consequently, 1 and 2 were skipped. We searched for "business process management" and "compliance" which includes both "regulatory compliance" and "legal compliance".

\newpage

## Study selection criteria {#sec-study-selection-criteria}

The quality of an article is assessed on the basis of the 4 criteria(QA1 through QA4). The criteria are equally weighted. An article is assigned 1 point for every QA criterium that is met. An article will thus get score of 0 through 4. Other metrics like author h-index and journal impact factor will not be considered in the selection process. 

| criteria   | code | descriptions                                               |
|------------|------|------------------------------------------------------------|
| inclusion  | IC1  | the title, abstract and full text are in english           |
|            | IC2  | the publication is dated between 2000 and 2024             |
|            |      |                                                            |
| exclusion  | EC1  | the reference is to a book(chapter)                        |
|            | EC2  | the article has been retracted                             |
|            | EC3  | the type of article is a conference paper or a preprint    |
|            | EC4  | a search term has a different meaning                      |
|            | EC5  | the application relates to a specific sector               |
|            | EC6  | the title, abstract and full text are not in english       |
|            |      |                                                            |
| quality    | QA1  | the article is a peer-reviewed journal article             |
|            | QA2  | the article appeared in one of the legible [journals](#appendix-b)|
|            | QA3  | has a citation count higher than 5 per year since the year of publication |
|            | QA4  | the first and second author have combined more than 50 publications listed on google scholar|
: Study selection criteria {#tbl-selection-criteria}

## Data extraction strategy {#sec-data-extraction-criteria}

The innitial 6 data sources have been reduced to 4 (excluding Zenodo). For the remaining 5 datasources queries will be formulated for each data source. The resulting records found will be listed in and excel file "slr_logbook.xlsx".

# Review execution{#sec-review-execution}

## Research identification

Initially 6 queries have been run against the 6 databases resulting in 84 hits as shown in @tbl-result-set in [appendix E](#appendix-e).
After testing the initially formulated 6 queries have een reduced to 4 queries.
The first two queries search for "business process management" or BPM in the title. The last two queries search for "business process engineering" or business process reengineering" in the title. 

1. TI=("business process management" or BPM) AND (AB=(compliance) OR KP=(compliance))
2. TI=("business process management" or BPM) AND (AB=("regulat\*") OR KP=("regulat\*"))
3. TI=("business process *engineering") AND (AB=(compliance) OR KP=(compliance))
4. TI=("business process \*engineering") AND (AB=(regulat\*) OR KP=(regulat\*))

The initial list (@tbl-database-searches) contains a total of 84 records. An additional 6 records were found from other sources (@tbl-other-sources). The total is 90 records. This list includes preprints and conference papers. Filtering the journal articles results in a list of 25 records (@tbl-review-abstracts).

In the case of Web of Science (WoS) the four queries have been taken together using the "OR" operator. This final query yields 42 results when using the the Vlerick WoS subscription[^1]. The search strings have be adapted to suit the specific requirements of the databases.

[^1]: Web of Science: Core Collection  
Subscription  : Vlerick Business School  
Editions  : A&HCI , ESCI , CPCI-SSH , CPCI-S , SCI-EXPANDED , SSCI  
Date range: 2014-2024  

<!--The total number of records of the 5 resulting ris files is xx. -->

## Selection of studies

The initial searches were done on all database fields. The search was subsequently made more specific by searching titles and abstracts. Lastly we searched titles, abstracts and keywords.

Across the 6 datasoures 84 articles have been identified, and an additional 6 records have been added from different sources. The found records are listed in [Appendix E](#appendix-e): @tbl-database-searches and @tbl-other-sources.

The process to get to the final {{<var literature.journal_articles>}} papers included in this literature study is visualized in the flowchart in @fig-slr-flowchart in [Appendix C](#appendix-c).

The WoS search yielded 29 hits. Excluding 4 articles with BPM in the title where BPM has a different meaning than "Business Process Management". For example where BPM is an abbreviation of "Biodiesel Particulate Matter". Excluding 1 article as it is a double, also ocuring in the dblp search.

The SD search yielded 7 hits. On the basis of article type (1 book chapter and 1 short communication) we have excluded two articles. An additional article was excluded as the title referred to "Business Process Management Map", which is a different concept. 

The SSRN search yielded 2 results, both excluded as they are preprints.

The arXiv search yielded 0 records when looking for articles with "Business Process Management" or BPM in the title field. Two records where found on the basis of abstract and keyword matches. All the same these records have been subsequently excluded when the exclusion criteria have been applied.

The dblp search yielded 41 records, including 2 books and 35 conference papers. After exclusion 4 records remain, 3 journal articles and one PhD thesis. For the next step, the abstract scan, the thesis has been replaced by a journal article by the same author about the same topic.

The Zenodo search yielded 0 records when looking for articles with "Business Process Management" or BPM in the title field. <!-- Four records where found on the basis of abstract and keyword matches. All the same these records have been subsequently excluded when the exclusion criteria have been applied. -->

Six additional records have been included identified via different sources: 4 journal articles, 1 PhD thesis and 1 conference paper. Here too, for the next step in the process the thesis has been replaced by a journal article by the same author about the same topic.

In summary:

|Database  | Found|Additional|Subtotal|Excluded|Result set|
|----------|-----:|---------:|-------:|-------:|---------:|
| WoS      | 29   |          |     29 |    -19 |    10    |
| SD       |  7   |          |      7 |     -7 |     0    | 
| SSRN     |  0   |   +2     |      2 |     -2 |     0    |
| arXiv    |  0   |   +4     |      4 |     -4 |     0    |
| dblp     | 42   |          |     42 |    -37 |     5    |
| zenodo   |  0   |          |        |        |     0    |
| aditional|  0   |   +6     |      6 |        |     6    |
|          |------|----------|--------|--------|----------|
| total    | 78   |  +12     |     90 |    -69 |    21    |

: Result set {#tbl-result-set}

The abstracts of the remaining 21 articles are listed in [Appendix G](#appendix-g), @tbl-review-abstracts.

## Study Quality Assessment

The first quality indicator is about the type of journal. Peer reviewed articles are deemed to be of better quality than, for example, conference papers. The second quality indicator is an a indirect measure of both the quality of the journal and the relevance of the article to the Information Systems field. The third quality indicator is a proxy for the quality of the article. The fourth indicator is deemed to be representative for the quality of the scholars.

The outcome for QA1 through QA4 is either 1 or 0 (1 means yes, 0 means no).  
QA1: the article is of the type peer-reviewed journal article  
QA2: the journal is in the eligible journals list   
QA3: the article has been referenced an average of 5 times per year since publication   
QA4: author 1 and author 2 have together authored at least 50 articles  
The detail of the calculation for QA3 en QA4 is shown in [appendix F](#appendix-f).


```{python}
#| label: tbl-quality-assessment
#| tbl-cap: "Quality assessment"

from IPython.display import Markdown
from tabulate import tabulate
from lib.my_excel_lib import get_tables
from lib.my_custom_lib import xls2md

tables = get_tables('tables/slr_logbook.xlsx')

Markdown(tabulate(
  xls2md(tables['quality_assessment']),
  headers=['Seq','Source','QA1','QA2','QA3','QA4','Score'],
  missingval=".",
  maxcolwidths=[2, 8, 8, 8, 8, 8, 8],
  showindex=False,
  colalign=('left', 'left', 'center', 'center', 'right','right','center')))
```

For the final list we only consider the {{<var literature.fulltexts_included>}} articles where three or more conditions are met (see: [appendix E](#appendix-e), @tbl-full-text-included).

## Data collection

The output of each query has either been a bib file or a ris file. All bib files have been converted to ris files. The mapping of bibliographic elements to the ris fields differs per data sources (see @tbl-ris-fields). A script has been written to get to a uniform ris-format [Appendix C](#appendix-c). 

The open access databases do not contain the full text articles if the articles are not open access. DBLP also doesn't contain abstracts. The absence of full text articles or abstracts is explained by constraints imposed by copyrights.

The excel file containing the article lists has been stored on zenodo for future reference ([zenodo 10795823](https://zenodo.org/records/10795823)).

## Synthesis of extracted data

<!--Relevant literature and identify topics listed as possibilities for future -->

8-12 years ago: the two oldest papers in the dataset are @vanderfeestenProductbasedWorkflowSupport2011 and @hadaschInfluenceDirectiveExplanations2016. The article of Irene Vanderfeesten is on the subject of her PhD thesis (@vanderfeesten2011product). It describes the concept of a Product Data Model which, in workflow systems, can be compared to a Bill of Material in manufacturing systems. The article doesn't mention future research but does mention collaboration with industrial partners to incorporate a PDM in a commercial tool. The Hadasch paper is a quantitive study about users' process compliance as a function of process explanations either in textual or diagram format (DE/DDE). Broadly stated, the paper concludes that the better explanations result in better compliance. Other than a recommendation that the findings of the paper be leveraged in future research, there is no specific guidance about future research.

4-8 years ago: the four papers published in the 2016-2019 timeslot are @vanderaalstSpreadsheetsBusinessProcess2018, @DBLP:journals/ail/HashmiG18, @hashmiAreWeDone2018 and @vanderaaComparingTextualDescriptions2017. The van der Aalst paper compares and contrasts spreadsheet technology with process mining technology. It mentions checking for compliance as the activity whereby a process as run in reality is compared to a normative model. The article mentions future process mining research should be about automatically improving processes by changing underlying process models. The first Hashmi paper compares six Compliance Modeling Frameworks (CMFs). There are two pointers to future research directions. 1) Studying the formal semantics of the norms modeling languages. 2) Studying the useability of the norms modeling constructs in practice. The second Hashmi paper is a SLR where 79 papers were included in the study. The study provides a comprehensive overview of the attributs of compliance in BPM. There is a general direction for future research given: to improve modeling languages to take into account all compliance requirements.
The article by van der Aa et al. is about the possible divergence of process descriptions and graphical process models. A quantitive analysis is performed on 53 real-life model-text pairs. One of the suggested future research directions is to also capture process information in other formats. Among the examples given of such other formats are rules and regulations.

0-4 years ago: the three most recent papers in the set are the papers  and @kirKnowledgeintensiveAdaptiveBusiness2021, @bernardojuniorAgileBusinessProcess2023 and @viriyasitavatBlockchainasaServiceBusinessProcess2023. The Kir paper introduces *agile*BPM, a modeling methodology. The main differentiator is that next to control flow *agile*BPM also caputers knowledge, rules and goals. A prototype of the system is compared to other similar systems (ADEPT, SmartPM, Planlets, Go4Flex). The paper doesn't mention future research. The Bernardo paper includes a SLR, interviews and expert consultations. Agile BPM is defined. Future research is suggested to be on practices necessary for emperical application of BPM in organizations. The Viriyasitavat article is a SLR on the use of blockchain technology for business process compliance. The paper argues that blockchain technologies can and are applied for business process compliance. Existing work has a focus on technical implementation of the functionalities of traditional BPM systems. However the use of blockchain technologies also allows for new functionalities. The further research section specifically mentions organizational and legal aspects. 

|  | Year |Article       | Alignment Concepts             | Future Research     |
|--|------|--------------|------------------------------- |---------------------|
| 1| 2011 |Vanderfeesten et al.|ProductData Model         | N                   |
| 2| 2016 |Hadasch et al.   |(Diagram)Descriptive Explanations  | N             |
| 3| 2017 |Van der Aa et al.| Consistency between representation| Y (specific)  |
| 4| 2018 |Van Der Aalst  |Prescriptive Analytics         | Y (general)         |
| 5| 2018 |Hashmi et al.  |Compliance Modeling Frameworks   | Y (specific)      |
| 6| 2018 |Hashmi et al.  |Compliance Modeling Languages    | Y (general)       |
| 7| 2021 |Kir et al.     |Context Awareness / Norm adoption| N                 |
| 8| 2023 |Viriyasitavat et al.  |Blockchain              | Y (general)         |
| 9| 2023 |Bernardo Junior et al.|      -                 | Y (general)         |

: Relevance to research question {#tbl-relevance-to-research-question}

All papers mention approaches for alignment of business processes with regulatory requirements except the Bernardo Junior paper about agile BPM. 

From these 9 papers reviewed, 6 mention future research directions. Two papers mention specific future research topic, for example around "consistency between different process representations" and "the useability of norm modelling constructs".

<!-- 
Businesses can identify relevant regulatory requirements through a comprehensive approach that involves understanding and analyzing various sources of compliance mandates. These sources include legislation and regulatory bodies (e.g., Sarbanes-Oxley and Basel II), standards and codes of practices (e.g., ISO 9001), and business partner contracts.

regulatory compliance and legal compliance

legislation and regulatory bodies

....

Goedertier and Vanthienen

Three articles are about the use of blockchain for BPM @anjumBlockchainStandardsCompliance2017 and @mendlingBlockchainsBusinessProcess2018 and @viriyasitavatBlockchainasaServiceBusinessProcess2023. The latter is a systematic literature about blockchain technology applied to servicing business processes. Chapter V is about business process compliance. Chapter VI details various applications such as the use of smart contracts as a Service for Controls of business processes (p7). This concept is of interest to this review (RD1).

Logic ()

Languages like BPMN-Q and LegalML

Semantics /textual + @vanderaaComparingTextualDescriptions2017 and @yipSemanticallyEnabledApplications2012 and @kharbiliFrameworkSemanticBusiness2008

@hashmiAreWeDone2018

From Science Direct @holzmuller-laueImprovedComplianceBPMDriven2014, 

Several publications (1,2,3) mention both compliance and conformance of business processes.
Compliance is externally imposed and legally binding, focusing on meeting regulatory and legal requirements (source). Conformance is about meeting standards and specifications to ensure quality and reliability, which can be a voluntary process driven by internal or external standards (source). In the context of this literature we are interested in compliance. Compliance requires translation of external rules to internal business rules. For conformance the translation

Does the business process exist outside of the organization. xxx and yyy reference a category of business processes they label cross-organizational business processes. As the name implies ...
On one hand of the spectrum there is a desire for governmental bodies to take into account (semi-)automated execution by companies. On the other side of the spectrum there is a "plea for instruments assessing the impact of policies on organizations prior to implementation" @gongPolicyImplementationBusiness2012. In the middle, presumably, is where the efforts are concentrated
-->
<!---
Conformance refers to the act of adhering to a set of standards or requirements. It involves ensuring that a product, service, or system meets the specified expectations and performs as intended. Conformance can be viewed as a proactive approach to quality management, where the focus is on preventing defects and errors from occurring in the first place.

Conformance often involves the use of quality management systems, such as ISO 9001, which provide a framework for organizations to establish and maintain a culture of quality. These systems typically involve a set of procedures and processes that are designed to ensure that products and services consistently meet customer requirements and comply with relevant regulations.

....
-->

# Review Reporting{#sec-review-reporting}

## Dissemination strategy

A subsequent version of this review will be part of the PhD work. The aim is to get three by-products out of this review:

- A poster that explains this literature review process and its results to be presented on a research day.
- A version of the software script that is installable and useable by somebody else.
- An open access publication.

<!--
Workflow management system
Business process management
Legal compliance
Regulatory compliance

https://www.planetcompliance.com/legal-and-regulatory-compliance/

[Compliance](https://thecontentauthority.com/blog/conformance-vs-compliance)
[Conformance](https://thecontentauthority.com/blog/conformance-vs-compliance)

Product Data Model (source)
Product Data Model (different source)
Object centric process mining
-->

## Limitations

The database searches resulted in a set of relevant articles for the subject of this review. Selecting a different set of databases would have resulted in a different set of relevant articles. The selection of databases was made from the databases available to us. We did not consider databases that require additional payment for access.

It is also noted that search results may defer among different databases. If the content of two databases is identical, the same query run against both databases can yield different results. The differences stem, among others, from different search fields, different query languages, different API's and different search engines. Examples of notable differences are:

- for WoS: the search results may differ depending on the subscription that is available to the user.
- for SD: the search results may differ as query's are interpreted based on language heuristics ([source](https://service.elsevier.com/app/answers/detail/a_id/35970/supporthub/sciencedirect/)). Also, SD does not support wildcards.
- for dblp: the *CompleteSearch* engine autocompletes search terms, see @bastTypeLessFind2006.
- for arXiv: wildcards can not be used as the first character of a search term ([source](https://www.arxiv.org/multi?%2Ffind=Search/)). For example "*engineering" will trigger an error message.

To assess the quality of the 21 identified articles a set of 4 indicators has been considered. There are many other indicators which can be used to assess the quality of an article. Changing the number of indicators and/or changing the selection of parameters could alter which full text articles are selected for the review.

## Future research

In follow-on research it maybe interesting to include openAIRE (Open Access Infrastructure for Research in Europe) as a data source. @schummBusinessProcessCompliance2010, p. 11 reference research that has been performed under the 2008-2011 [COMPAS](https://cordis.europa.eu/project/id/215175) research project funded by the EU and coordinated by the Technische Universitaet Wien. More information about the research output of these projects will be available via OpenAIRE. When OpenAIRE will be included as a data source we will also again include Zenodo. Zenodo was created as part of the OpenAIRE initiative.

For reproducibility a future version of this literature review shall have the protocol altered. For commercial databases one and the same query can yield different results if it is run with two different licenses. This has been found to be the case with Web of Science. For the query used in this review the Vlerick Business School license of WoS yielded 42 hits while the Amsterdam University of Applied Sciences license of WoS yield 24 hits (to be included in appendix). It is assumed the average user does not have precise information of the licenses that Academic institutions hold. As such WoS is better not used in the early stages of the search. The protocol could instead dictate the use of open databases, such as OpenAlex, for the early stages of the search. Commercial databases would then be used in a later stage to get abstracts and full texts of selected articles that are not available from open databases.

For quality assesment we have now used a self-constructed indicator (QA4) that has as inputs the number of publications by the first and second author. If further research is conducted it can be considered to replace this indicator with the ubiguitous h-index (@WOS:000615174400014). Also, the fact that only 1 article is from the eligible journals list seems to indicate that either the list needs to be revised. Alternatively a different indicator, such as the journal impact factor, can be a substitute quality indicator.

Finally, where it relates to compliance checks, in the literature there is a divide between "design time" and "run time". As the RQ of this research refers to \fbox{compliance by design}, future research may have more of different search terms to also filter research about "design time" compliance checking.

<!--
Did we miss searching for "compliance by design"? Did we miss searching for "inter organizational processes"?  
In practice the term "workflow management system" is used in financial institutions (bron: Mark Muyres).


\newpage

**Search Strings Used**


Web of Science:

(TI=("business process" management or BPM) AND (AB=(compliance) OR KP=(compliance))) OR (TI=("business process" management or BPM) AND (AB=(regulat*) OR KP=(regulat*))) OR (TI=("business process *engineering") AND (AB=(compliance) OR KP=(compliance))) OR (TI=("business process *engineering") AND (AB=(regulat*) OR KP=(regulat*)))

DBLP:
- "business process management" compliance
- "business process management" regulat*
- "business process *engineering" compliance
- "business process \*engineering" and regulat*

ScienceDirect:
title="business process management" and tka=compliance or regulation or regulatory or engineering or reengineering or design

Zenodo:  
+title:"business process management" +regulat* OR compliance +resource_type.type:publication

\newpage
-->