---
project:
  type: default
  output-dir: output
title: "SLR"
subtitle: "Aligning business processes with regulatory requirements"
date: "02-24-2024"
date-format: "D/MM/YYYY"
date-modified: "10-23-2023"
author:
  - name:
    orcid: 0000-0003-1689-0557
    email: j.r.muller@hva.nl
    affiliations:
      - name: Amsterdam University of Applied Sciences
        address: Fraijlemaborg 133
        city: Amsterdam
        postal-code: 1102 CV
      - name: Vlerick Business School
        address: Reep 1
        city: Ghent
        postal-code: 9000
abstract: ""
format:
  pdf:
    cite-method: citeproc
    include-in-header: 
      text:
        \usepackage{imakeidx, bibentry, scrlayer-scrpage}
        \rohead{Draft}
        \lofoot{}
latex-output-dir: output
papersize: a4
execute:
  echo: false
toc: false
toc-depth: 2
bibliography: MyLibrary.bib
keywords: modelling languages, controlled natural language

---

## Background

In the context of the DBA program at Vlerick Business School a literature review is one of the deliverables of year two.

## Conceptual model

There is an existing model published by OCEG (&Refinitiv) that may be used as a reference. The 2018 version is attached and redrawn below (@RegulatoryChangeManagement2018).

{{< include diagrams/s2_oceg_regulatory_change_process.qmd >}}

## Research questions

The main research question RQ

RQ: What are approaches for aligning business processes with regulatory requirements to achieve regulatory compliance by design?

RQ: What are approaches for aligning \fbox{business processes} with \fbox{regulatory requirements} to achieve regulatory \fbox{compliance by design}?

SQ-1: How can businesses identify relevant regulatory requirements? 

Businesses can identify relevant regulatory requirements through a comprehensive approach that involves understanding and analyzing various sources of compliance mandates. These sources include legislation and regulatory bodies (e.g., Sarbanes-Oxley and Basel II), standards and codes of practices (e.g., ISO 9001), and business partner contracts.

SQ-2: How can businesses analyze which business processes are affected by changes in requlatory requirements? 

SQ-3: How can businesses integrate compliance requirements into business process design?

SQ-4: How can businesses ensure compliance throughout the lifecycle of the impacted business processes?

## Search terms

1. ("business process management" or BPM) and "regulatory compliance"
2. ("business process management" or BPM) and "legal compliance"
3. ("business process management" or BPM) and "compliance"
4. "business process management" and ("regulation" or "regulatory")
5. "business process *engineering" and "compliance"
6. "business process *engineering" and ("regulation" or "reglatory")

## Search queries

The search query is composed of four individual queries. The first two queries search for "business process management" or BPM in the title. The last two queries search for "business process engineering" or business process reengineering" in the title. 

1. (TI=("business process management" or BPM) AND (AB=(compliance) OR KP=(compliance))) OR 
2. (TI=("business process management" or BPM) AND (AB=("regulat*") OR KP=("regulat*"))) OR 
3. (TI=("business process *engineering") AND (AB=(compliance) OR KP=(compliance))) OR 
4. (TI=("business process \*engineering") AND (AB=(regulat\*) OR KP=(regulat*)))

this query yields xx results on the Vlerick WoS subscription (core ...) which is limited to 10 years back.

Table search query

| Type               |Abbrev.        | Name                               |Possible contact                    | 
|--------------------|---------------|------------------------------------|------------------------------------|
| Trade association  |[NVB][NVB1-ref]| Nederlandse Vereniging van Banken  |                                    |
: Search {.striped .hover}

[NVB1-ref]: https://www.nvb.nl/

## Resources to be searched

|Platform      | Operator  |
|--------------|-----------|
|Web of Science|[Clarivate](https://www-webofscience-com) |
|ScienceDirect |[Elsevier](https://www-sciencedirect-com) |
|SSNR          |[Elsevier](https://www.ssrn.com/)         |
|arXiv         |[cs](https://arxiv.org/search/cs)         |
|dblp          |[dblp](https://dblp.org/)                 |
|Zenodo        |                                          |

: Resources {.striped .hover}

## Study selection criteria

To be completed !!!

## Study quality assessment

- peer-reviewed journals
- conference papers
- book articles

## Data extraction strategy

Queries have been formulated for each datasource. Where queries could be specified at a field level (WoS and SD) we looked for "business process management" in the title field.

|Date | Search ID | Title | Keywords | Abstract | Query Link | Hits |
|-----|-----------|-------|----------|----------|------------|------|
|     |           |       |          |          |            |      |
: Hits {.striped .hover}

(TI=("business process management" or BPM) AND (AB=("compliance") OR KP=("compliance"))) or 
(TI=("business process management" or BPM) AND (AB=("regulat*") OR KP=("regulat*"))) 1. first


Footnote
Web of Science: Core Collection
Subscription  : Vlerick Business School
Editions  : A&HCI , ESCI , CPCI-SSH , CPCI-S , SCI-EXPANDED , SSCI  
Date range: 2014-2024  

## Synthesis of extracted data

SQ1  

SQ2  

SQ3  

SQ4  

## Disseminaton strategy

Prelim conclusion and future work go here?

\newpage

## Examples of SLR

[05/10/2023] Looking in my Zotero library for articles with a title that contains "systematic literature review", the result is 7 hits:

- The first is @kitchenhamGuidelinesPerformingSystematic2007 and there is a duplicate @keeleGuidelinesPerformingSystematic2007.
- Second there are 3 SLR's where Van Looy is co-author (@moreno-montesdeocaSystematicLiteratureReview2015, @prodanovaHowBeneficialSocial2019, @ahmadBusinessProcessManagement2020).
- There is 1 SLR about BPMN extensions (@zarourSystematicLiteratureReview2019)
- Finally, there is one SLR about Open Science (@VICENTESAEZ2018428) which is not relevant to BP4RC.


## Definitions (Glossary?)

Workflow management system

Business process management

Legal compliance

Regulatory compliance

https://www.planetcompliance.com/legal-and-regulatory-compliance/

[Compliance](https://thecontentauthority.com/blog/conformance-vs-compliance)

[Conformance](https://thecontentauthority.com/blog/conformance-vs-compliance)

Conformance refers to the act of adhering to a set of standards or requirements. It involves ensuring that a product, service, or system meets the specified expectations and performs as intended. Conformance can be viewed as a proactive approach to quality management, where the focus is on preventing defects and errors from occurring in the first place.

Conformance often involves the use of quality management systems, such as ISO 9001, which provide a framework for organizations to establish and maintain a culture of quality. These systems typically involve a set of procedures and processes that are designed to ensure that products and services consistently meet customer requirements and comply with relevant regulations.

Product Data Model (source)

Product Data Model (different source)

Object centric process mining

## Limitations

projecten, sinds 2014 (@tbl-resultset). 

## Future

Did we miss searching for "complaince by design"? Did we miss searching for "inter organizational processes"?  
In practice the term "workflow management system" is used in financial institutions (bron: Mark Muyres).

|Platform |Operator   |Note                                             | Article |
|---------|-----------|-------------------------------------------------|---------|
|Scopus   |[Elsevier](www-scopus-com)| note: not available via Vlerick  |    (@priemOpenAlexFullyopenIndex2022)     |
|OpenAlex |[OpenAlex](https://openalex.org) |                           |         |
|OpenAIRE |[OpenAIRE](https://explore.openaire.eu/) | Mentioned in connection with Zenodo and also EU Research Programs | |
: Further Resources {.striped .hover}


\newpage

## Appendix - Tabels

{{< include tables/s2_tbl_platforms.qmd >}}

\newpage

another transformation before this one
(formula for transformation?)

input / output

{{< include tables/s2_tbl_ris_fields_per_source.qmd >}}

alternate grey/white for readability (python table?)

Reference wikipedia page [RIS format](https://en.wikipedia.org/wiki/RIS_(file_format))

\newpage

{{< include tables/s2_tbl_query_results.qmd >}}

\newpage

## RCM Process Steps

1. Identify & Define  
1.1 Develop Company Profile  
1.2 Apply Regulatory Content Taxonomy  
1.3 Establish Risk Based Regulatory Library  
2. Track & Analyze  
2.1 Track Relevant Regulatory Actions  
2.2 Compare and Analyze  
2.3 Maintain Regulatory Library  
3. Monitor & Map  
3.1 Monitor Regulatory Events to Affected Areas  
3.2 Evaluate Need for Control/Actions Changes  
3.3 Notify/Control Policy Owners  
4. Control & Manage  
4.1 Evaluate Flagged Impacts on Controls/Actions and Operations  
4.2 Determine Changes, Implement and Record  
4.3 Identify Exceptions and Record Reasons/Alternatives  
5. Report & Record  
5.1 Continuously Monitor and Analyze  
5.2 Report Key Changes and Business Impacts  
5.3 Maintain Audit Trail of Compliance  

\newpage

## Software used

All of the scripts use pandas (reback2020pandas).

We used various sofware scripts to assemple the dataset. Specificaly:

- [arxiv2bib](https://nathangrigg.github.io/arxiv2bib/), Get a BibTeX entry from an arXiv id number, using the arxiv.org API. ([Nathan Grigg](https://nathangrigg.com/), 2017)
- [bib2ris](https://github.com/MacDumi/bib2ris), Script to convert bibtex files to ris format. ([Dumitru Duca](https://orcid.org/0000-0002-3873-4224), 2020)
- [rispy](https://github.com/MrTango/rispy), A Python 3.8+ reader/writer of RIS reference files. (Version 0.9.0; [Maik Derstappen](https://www.linkedin.com/in/maik-derstappen-4ab80618/?locale=en_US), 2024)
- [tabulate](https://github.com/astanin/python-tabulate), Pretty-print tabular data in Python, a library and a command-line utility. ([Sergey Astanin](https://scholar.google.com/citations?user=DWdSLeMAAAAJ&hl=en&oi=sra), 2022)

\newpage

\fontsize{8}{9}\selectfont

```{python}
#| label: tbl-resultset
#| tbl-cap: ResultSet
#| 
from IPython.display import Markdown
from tabulate import tabulate
from lib.my_excel_lib import get_tables
from lib.my_custom_lib import xls2md

tables = get_tables('tables/slr_logbook.xlsx')

Markdown(tabulate(
  xls2md(tables['ResultSet']),
  headers=['Nr','Type','Title'],
  missingval=[''],
  maxcolwidths=[3, 10, 100],
  showindex=False,
  colalign=('left', 'left','left')))

```

\newpage

## Literature
