---
format: pdf
tbl-cap-posion: bottom
bibliography: "references.bib"
---
# Journals

From a podcast by @ThisIsResearch, I understand in the field of IS research there is a "basket of 8" authoritive journals (table 1). The columns: level, impact factor (IF), Association of Business Schools (ABS), Harzing are taken from the Vlerick Strategic Journal List (the List),effective as of January 2020. Empty means the journal is not on the List.

| Journal Title                                                              |Level| IF  |
|----------------------------------------------------------------------------|:---:|:---:|
| MIS Quarterly ([MISQ][MISQ-ref])                                           | A*  |7,268|
| Journal of Management Information Systems ([JMIS][JMIS-ref])               | A*  |2,744|
| Information Systems Journal ([ISJ][ISJ-ref])                               | A   |4,267|
| Journal of the Association for Information Systems ([JAIS][JAI-ref])       | A   |2,839|
| Communications of the Association for Information Systems ([CAIS][CAI-ref])| A   |  ?  |
| Information Systems Research ([ISR][ISR-ref])                              | A*  |2,301|
| Journal of Information Technology ([JIT][JIT-ref])                         | A   |4,435|
| European Journal of Information Systems ([EJIS][EJIS-ref])                 | A   |2,819|

: Basket of 8 {#tbl-journals}

[MISQ-ref]: https://misq.umn.edu/
[JMIS-ref]: https://jmis-web.org/
[ISJ-ref]: https://onlinelibrary.wiley.com/journal/13652575
[JAI-ref]: https://aisel.aisnet.org/jais/
[CAI-ref]: https://aisel.aisnet.org/cais/
[ISR-ref]: https://pubsonline.informs.org/journal/isre
[JIT-ref]: https://journals.sagepub.com/home/jina
[EJIS-ref]: https://www.tandfonline.com/toc/tjis20/current

The list of 8 premier journals exists since 2011. The list has been updated in 2023 to include an additional 3 journals.

| Journal Title                                                              |Level| IF  | 
|----------------------------------------------------------------------------|:---:|:---:|
| Decision Support Systems ([DSS][DSS-ref])                                  |  A  |2,819|
| Information & Management ([IAM][IAM-ref])                                  |  A  |3,890|
| Information and Organization ([IAO][IAO-ref])                              |     |     |

: Recent additions {#tbl-journalsb}

[DSS-ref]: https://www-sciencedirect-com/journal/decision-support-systems
[IAM-ref]: https://www.sciencedirect.com/journal/information-and-management
[IAO-ref]: https://www-sciencedirect-com/journal/information-and-organization

Next to the basket of 8 (now 11) there are other journals that I will want to search articles from. BISE is of interest because it is an european (IS) journal (as is EJIS). BPMJ and IJDG may be of interest given the subject matter their titles refer to. SMR I find of interest as it focusses on the intersection of Management and Technology. On the topic of work design and agility I may want to reference works of [Nelson Repenning](https://mitsloan.mit.edu/faculty/directory/nelson-p-repenning). HBR maybe of interest for the (historic) articles on business process reengineering by [Michael Hammer](https://hbr.org/2008/10/remembering-mike-hammer).

| Journal Title                                                            |Level| IF  |
|--------------------------------------------------------------------------|:---:|:---:|
| Business Process Management Journal ([BPMJ][BPMJ-ref])                   |     |     |
| Business & Information Systems Engineering ([BISE][BISE-ref])            |     |     |
| Journal of Disclosure and Governance ([IJDG][IJDG-ref])                  |     |     |
| Sloan Management Review ([SMR][SMR-ref])                                 | A*  |0,971|
| Harvard Business Review ([HBR][HBR-ref])                                 | A*  |0,720|

: Other journals of interest {#tbl-journalsc}

[BPMJ-ref]: https://www.emeraldgrouppublishing.com/journal/bpmj
[BISE-ref]: http://www.bise-journal.com/
[IJDG-ref]: https://www.palgrave.com/gp/journal/41310
[SMR-ref]: https://sloanreview.mit.edu/
[HBR-ref]: https://hbr.org/

In terms of "where does one aim to be published", for an entirely different type of journal:

| Journal Title                                                            |Level| IF  |
|--------------------------------------------------------------------------|:---:|:----|
| Journal of Open Source Software ([JOSS][JOSS-ref])                       |     |     |

: Yet other journals of interest {#tbl-joss}

[JOSS-ref]: https://www.emeraldgrouppublishing.com/journal/bpmj

JOSS doesn't show on any of the quality journal lists. Yet, it seems an appropriate outlet for part of the work produced in the context of my PhD research. My research follows a design science methodology. "In order to add science to Design Science, developed artifacts need to be properly evaluated" [@mijacEvaluationDesignScience2019].

It is important to define the field the research is positioned in: I still will look into "business informatics". This is a term less used in the U.S. and more used in the E.U. ("bedrijfsinformatica" in Dutch and "wirtschaftsinformatik" in German).

# References {.unnumbered}

::: {#refs}
:::

\newpage

Define h-score
Define A star journal


| # | Article |  |  | GSReferences | Published in | Journal Score | Principal Author | H-Factor |
|---|---------|--|--|--------------|--------------|---------------|------------------|----------|
| 1 |         |  |  | 1            |              |               |                  | G -      |
| 2 | C4 -    |  |  | 2            |              |               |                  | G3 -     |
| 3 | C44 -   |  |  | 3            |              |               |                  | G33 -    |



An example of a potentially relevant article in BPMJ:

An example of a potentially relevant article in Disclosure and Governance:

# Databases

Research question
Searched sources
Search terms
Search strategy
Inclusion criteria
Exclusion criteria
Quality criteria

**Ranking**

* Citation Impact (CiteScore, Clarivate Journal Citation Indicator, Journal Impact Factor)

* Usage (full text views)

* Speed (acceptance rate, submission to first decision)

**Databases / Repositories**

[dblp computer science bibliography](dblp.org)


**Alternatives for Microsoft Open Graph**

- Aminer
- CrossRef
- Dimensions
- lens.org
- OpenAlex.org
- OpenCitations
- Scopus
- Semantic Scholar


**Other info for separate document**

1. International Journal of Lean Six Sigma ([JLSS][JLSS-ref])
[JLSS-ref]: https://www.emeraldgrouppublishing.com/journal/ijlss

Maybe seperately list institutes:
- TNO
- Frauenhoffer
- SEI (CMU)