---
format: 
    html

---

Plaatje van een toolbox erboven.

To me, the PhD is about: 

- learning to do the research 
- learning the tools to do the research
- do the research
- use the tools to do the research

This page is about the resources I have come across and that were of help resolving small and big issues I've come across.

# Technical Resources

Separately there shall be a list of websites like:

[Process Mining](https://www.processmining.org/)

https://fredguth.github.io/IBToDL/IBToDL.pdf

- [TexFAQ](https://texfaq.org/FAQ-LaTeX2HTML)

plasTeX is a Python package to convert LaTeX markup to DOM
[plasTEx](https://plastex.github.io/plastex/)

https://stacks.math.columbia.edu/statistics

using quarto (in vs-code). The yaml header 


What is the problem I encountered:

I was having issues with the citations. Reading the quarto documentation I found a "cite-method" can be defined. This led me to reading about citeproc, biblatex and natbib. On stackoverflow I eventually found that I was mixing instructions in the YAML frontmatter. 

Not to forget: 

- \addbibresource{filename.bib} goes with biblatex
- Bibliography: "filename" goes with citeproc (which is quoarto's default)

What is the resource that helped me:

https://bookdown.org/yihui/rmarkdown/
stackoverflow
